#Rebuilding the Kaggle Dataset with csv from NTSB, 2008 - April 2023.
After completing the EDA of the Kaggle dataset and comparing it to the NTSB tables, it seems like we would get more usable data by parsing and aggregating the relevant columns from the NTSB tables

## First, upload the original csv from Canvas/Kaggle. 
(Flatiron got the dataset from [here](kaggle.com/datasets/khsamaha/aviation-accident-database-synopses).)

In [ ]:
from google.colab import files
uploaded = files.upload()

**Read the csv in as a dataframe using pandas.**

In [ ]:
import pandas as pd

In [ ]:
df_aviation = pd.read_csv('Aviation_Data.csv')

<ipython-input-3-66cba5241676>:1: DtypeWarning: Columns (6,7,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df_aviation = pd.read_csv('Aviation_Data.csv')


**Preview the dataframe using various methods.**

In [ ]:
df_aviation.shape

(90348, 31)

In [ ]:
df_aviation.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

**Make a list of the columns so that it is more readable.**

In [ ]:
aviaton_columns_list = list(df_aviation.columns)
aviaton_columns_list 

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date']

In [ ]:
df_aviation.info 

<bound method DataFrame.info of              Event.Id Investigation.Type Accident.Number  Event.Date  \
0      20001218X45444           Accident      SEA87LA080  1948-10-24   
1      20001218X45447           Accident      LAX94LA336  1962-07-19   
2      20061025X01555           Accident      NYC07LA005  1974-08-30   
3      20001218X45448           Accident      LAX96LA321  1977-06-19   
4      20041105X01764           Accident      CHI79FA064  1979-08-02   
...               ...                ...             ...         ...   
90343  20221227106491           Accident      ERA23LA093  2022-12-26   
90344  20221227106494           Accident      ERA23LA095  2022-12-26   
90345  20221227106497           Accident      WPR23LA075  2022-12-26   
90346  20221227106498           Accident      WPR23LA076  2022-12-26   
90347  20221230106513           Accident      ERA23LA097  2022-12-29   

              Location        Country   Latitude  Longitude Airport.Code  \
0      MOOSE CREEK, ID  Uni

In [ ]:
df_aviation['Investigation.Type'].unique

<bound method Series.unique of 0        Accident
1        Accident
2        Accident
3        Accident
4        Accident
           ...   
90343    Accident
90344    Accident
90345    Accident
90346    Accident
90347    Accident
Name: Investigation.Type, Length: 90348, dtype: object>

There are dates mixed in with the `'Investigation.Type' `column. Compare this to `'ev_type' `from NTSB wherein all there were two unique values: `ACC` (accident) and `INC` (incident).

In [ ]:

investigation_type_list = df_aviation['Investigation.Type'].tolist()
unique_investigation_type_list = set(investigation_type_list)
unique_investigation_type_list

{'01-06-2021',
 '01-07-2022',
 '01-09-2022',
 '01-11-2022',
 '02-02-2021',
 '02-12-2022',
 '03-06-2021',
 '03-11-2020',
 '03-11-2022',
 '03-12-2020',
 '04-03-2021',
 '04-08-2021',
 '05-01-2021',
 '05-04-2021',
 '05-05-2021',
 '05-07-2022',
 '05-08-2022',
 '06-01-2021',
 '06-05-2021',
 '06-10-2022',
 '07-12-2020',
 '08-06-2021',
 '08-09-2022',
 '08-11-2021',
 '08-12-2022',
 '10-06-2021',
 '11-02-2021',
 '11-12-2020',
 '12-08-2022',
 '13-07-2022',
 '13-09-2021',
 '13-10-2022',
 '13-12-2021',
 '14-06-2021',
 '14-06-2022',
 '14-12-2021',
 '15-07-2021',
 '15-10-2021',
 '15-12-2022',
 '16-07-2021',
 '16-11-2021',
 '17-12-2021',
 '18-11-2020',
 '19-10-2021',
 '19-11-2020',
 '20-05-2021',
 '20-07-2022',
 '20-08-2021',
 '20-09-2021',
 '20-10-2021',
 '20-12-2022',
 '22-06-2022',
 '22-09-2021',
 '22-09-2022',
 '23-09-2022',
 '24-02-2021',
 '24-06-2021',
 '24-08-2021',
 '25-05-2021',
 '25-09-2020',
 '26-01-2021',
 '26-08-2021',
 '26-09-2020',
 '27-05-2021',
 '28-01-2021',
 '29-01-2021',
 '29-09-20

#Uploading the NTSB tables

##Reading in and selecting columns from `aircraft.csv`

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving aircraft.csv to aircraft.csv


**Read the `aircraft.csv` as a dataframe using pandas.**

In [ ]:
df_aircraft = pd.read_csv('aircraft.csv')

<ipython-input-4-fc55b6345277>:1: DtypeWarning: Columns (0,59) have mixed types. Specify dtype option on import or set low_memory=False.
  df_aircraft = pd.read_csv('aircraft.csv')


**Preview the aircraft data using various methods.**

In [ ]:
df_aircraft.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key regis_no      ntsb_no acft_missing  \
0      20080211X00175             1   N530NA   DFW08RA039            N   
1      20080107X00026             1   N8037W  SEA08LA057A            N   
2      20080107X00026             2    N15EX  SEA08LA057B            N   
3      20080109X00036             1   N579RM   DFW08CA054            N   
4      20080107X00027             1    N398J   DFW08LA055            N   
...               ...           ...      ...          ...          ...   
25913  20230426107154             1    N140D   WPR23LA168            N   
25914  20230427107155             1   N751WW   ERA23LA210            N   
25915  20230427107158             1   C-FCPE   GAA23WA136            N   
25916  20230427107159             1  JA-395A   GAA23WA137            N   
25917  20230430107167             1   N575ND   WPR23FA172            N   

      far_part flt_plan_filed flight_plan_activated damage acft_fire  ...  \
0 

In [ ]:
df_aircraft.columns

Index(['ev_id', 'Aircraft_Key', 'regis_no', 'ntsb_no', 'acft_missing',
       'far_part', 'flt_plan_filed', 'flight_plan_activated', 'damage',
       'acft_fire', 'acft_expl', 'acft_make', 'acft_model', 'acft_series',
       'acft_serial_no', 'cert_max_gr_wt', 'acft_category', 'acft_reg_cls',
       'homebuilt', 'fc_seats', 'cc_seats', 'pax_seats', 'total_seats',
       'num_eng', 'fixed_retractable', 'type_last_insp', 'date_last_insp',
       'afm_hrs_last_insp', 'afm_hrs', 'elt_install', 'elt_oper',
       'elt_aided_loc_ev', 'elt_type', 'owner_acft', 'owner_street',
       'owner_city', 'owner_state', 'owner_country', 'owner_zip',
       'oper_individual_name', 'oper_name', 'oper_same', 'oper_dba',
       'oper_addr_same', 'oper_street', 'oper_city', 'oper_state',
       'oper_country', 'oper_zip', 'oper_code', 'certs_held', 'oprtng_cert',
       'oper_cert', 'oper_cert_num', 'oper_sched', 'oper_dom_int',
       'oper_pax_cargo', 'type_fly', 'second_pilot', 'dprt_pt_same_ev',
      

The aircraft key is important as allows us to differentiate between aircraft in the case of events involving more than one aircraft. Looking at the values and counts we see that most events involve only 1 aircraft, but 414 involve 2 aircraft and 3 events involved 3 aircrart. No events involved more than 3 aircraft from 2008 to April 2023.

In [ ]:
df_aircraft['Aircraft_Key'].unique()

array([1, 2, 3])

In [ ]:
df_aircraft['Aircraft_Key'].value_counts()

1    25501
2      414
3        3
Name: Aircraft_Key, dtype: int64

Looks like the `phase_flt_spec` column might not be useful.

In [ ]:
df_aircraft['phase_flt_spec'].values

array([nan, nan, nan, ..., nan, nan, nan])

`'far_part' `tells us which Federal Aviation Regulation applies to the aircraft.
More on Federal Aviation Regulations [here](https://bogidope.com/alphabet-and-number-soup-far-parts-explained/).

In [ ]:
df_aircraft['far_part'].unique

<bound method Series.unique of 0        NUSN
1         091
2         091
3         091
4         091
         ... 
25913     091
25914     091
25915    NUSN
25916    NUSN
25917     NaN
Name: far_part, Length: 25918, dtype: object>

In [ ]:
nan_count_far_part = df_aircraft['far_part'].isna().sum()
nan_count_far_part

679

In [ ]:
# adding far part in case there is interest
selected_columns = ['ev_id', 'Aircraft_Key', 'ntsb_no', 'regis_no', 'acft_category', 'acft_make', 'acft_model', 'homebuilt', 'far_part','num_eng', 'type_fly', 
               'damage']

df_aifcraft_og_replace2 = df_aircraft[selected_columns].copy()

In [ ]:
df_aifcraft_og_replace2.columns

Index(['ev_id', 'Aircraft_Key', 'ntsb_no', 'regis_no', 'acft_category',
       'acft_make', 'acft_model', 'homebuilt', 'far_part', 'num_eng',
       'type_fly', 'damage'],
      dtype='object')

In [ ]:
df_aifcraft_og_replace.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key      ntsb_no regis_no acft_category  \
0      20080211X00175             1   DFW08RA039   N530NA          HELI   
1      20080107X00026             1  SEA08LA057A   N8037W           AIR   
2      20080107X00026             2  SEA08LA057B    N15EX           AIR   
3      20080109X00036             1   DFW08CA054   N579RM           AIR   
4      20080107X00027             1   DFW08LA055    N398J           AIR   
...               ...           ...          ...      ...           ...   
25913  20230426107154             1   WPR23LA168    N140D           NaN   
25914  20230427107155             1   ERA23LA210   N751WW           NaN   
25915  20230427107158             1   GAA23WA136   C-FCPE           NaN   
25916  20230427107159             1   GAA23WA137  JA-395A           NaN   
25917  20230430107167             1   WPR23FA172   N575ND           NaN   

                    acft_make acft_model homebuilt  num_eng type_fl

In [ ]:
df_aifcraft_og_replace.columns

Index(['ev_id', 'Aircraft_Key', 'ntsb_no', 'regis_no', 'acft_category',
       'acft_make', 'acft_model', 'homebuilt', 'num_eng', 'type_fly',
       'damage'],
      dtype='object')

In [ ]:
df_aifcraft_og_replace.head(3)

ev_id  Aircraft_Key      ntsb_no regis_no acft_category  \
0  20080211X00175             1   DFW08RA039   N530NA          HELI   
1  20080107X00026             1  SEA08LA057A   N8037W           AIR   
2  20080107X00026             2  SEA08LA057B    N15EX           AIR   

           acft_make acft_model homebuilt  num_eng type_fly damage  
0  Eurocopter France    AS350B3         N      NaN     EXLD   SUBS  
1              PIPER  PA 28-180         N      1.0     PERS   MINR  
2    Barnard/Stancil    Glastar         Y      1.0     PERS   SUBS

In [ ]:
#exporting csv to google drive 
#from google.colab import drive
#drive.mount('/content/drive')
path = '/content/drive/My Drive/df_aifcraft_og_replace2.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_aifcraft_og_replace2.to_csv(f)

##Reading in and selecting columns from `events.csv`

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving events.csv to events.csv


In [ ]:
df_events = pd.read_csv('events.csv')

<ipython-input-18-3850d9eac6c9>:1: DtypeWarning: Columns (0,31,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df_events = pd.read_csv('events.csv')


In [ ]:
df_events.info

<bound method DataFrame.info of                 ev_id     ntsb_no ev_type            ev_date ev_dow  ev_time  \
0      20080211X00175  DFW08RA039     ACC  01/10/08 00:00:00     Th   1907.0   
1      20080107X00026  SEA08LA057     ACC  01/01/08 00:00:00     Tu   2230.0   
2      20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00     Tu   2200.0   
3      20080107X00027  DFW08LA055     ACC  01/03/08 00:00:00     Th    825.0   
4      20080115X00051  DEN08CA047     ACC  01/02/08 00:00:00     We   2230.0   
...               ...         ...     ...                ...    ...      ...   
25504  20230426107154  WPR23LA168     ACC  04/26/25 00:00:00     Sa    120.0   
25505  20230427107155  ERA23LA210     ACC  04/18/23 00:00:00     Tu   2310.0   
25506  20230427107158  GAA23WA136     ACC  04/14/23 00:00:00     Fr   1930.0   
25507  20230427107159  GAA23WA137     ACC  04/18/23 00:00:00     Tu   1002.0   
25508  20230430107167  WPR23FA172     ACC  04/30/23 00:00:00     Su    530.0   

      e

In [ ]:
df_events.head(3)

ev_id     ntsb_no ev_type            ev_date ev_dow  ev_time  \
0  20080211X00175  DFW08RA039     ACC  01/10/08 00:00:00     Th   1907.0   
1  20080107X00026  SEA08LA057     ACC  01/01/08 00:00:00     Tu   2230.0   
2  20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00     Tu   2200.0   

  ev_tmzn          ev_city ev_state ev_country  ...  ntsb_notf_from  \
0     UTC  Pitt Meadow, BC      NaN         CA  ...             NaN   
1     UTC           Sonoma       CA        USA  ...             NaN   
2     UTC           Arcola       TX        USA  ...             NaN   

   ntsb_notf_date  ntsb_notf_tm fiche_number          lchg_date lchg_userid  \
0             NaN           NaN          NaN  09/25/20 18:07:50         NaN   
1             NaN           NaN          NaN  09/25/20 18:05:31         NaN   
2             NaN           NaN          NaN  09/25/20 18:05:31         NaN   

  wx_cond_basic faa_dist_office dec_latitude dec_longitude  
0           NaN             NaN          NaN           NaN  
1           VMC             NaN    38.223888   -122.449722  
2           VMC             NaN    29.506111    -95.476669  

[3 rows x 73 columns]

In [ ]:
# checking for unique values of airport ID where event took place or close to
df_events['ev_nr_apt_id'].unique

<bound method Series.unique of 0        NaN
1        OQ3
2        AXH
3        PWA
4        FNL
        ... 
25504    NaN
25505    NaN
25506    NaN
25507    NaN
25508    NaN
Name: ev_nr_apt_id, Length: 25509, dtype: object>

In [ ]:
df_events.columns

Index(['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'ev_dow', 'ev_time',
       'ev_tmzn', 'ev_city', 'ev_state', 'ev_country', 'ev_site_zipcode',
       'ev_year', 'ev_month', 'mid_air', 'on_ground_collision', 'latitude',
       'longitude', 'latlong_acq', 'apt_name', 'ev_nr_apt_id', 'ev_nr_apt_loc',
       'apt_dist', 'apt_dir', 'apt_elev', 'wx_brief_comp', 'wx_src_iic',
       'wx_obs_time', 'wx_obs_dir', 'wx_obs_fac_id', 'wx_obs_elev',
       'wx_obs_dist', 'wx_obs_tmzn', 'light_cond', 'sky_cond_nonceil',
       'sky_nonceil_ht', 'sky_ceil_ht', 'sky_cond_ceil', 'vis_rvr', 'vis_rvv',
       'vis_sm', 'wx_temp', 'wx_dew_pt', 'wind_dir_deg', 'wind_dir_ind',
       'wind_vel_kts', 'wind_vel_ind', 'gust_ind', 'gust_kts', 'altimeter',
       'wx_dens_alt', 'wx_int_precip', 'metar', 'ev_highest_injury',
       'inj_f_grnd', 'inj_m_grnd', 'inj_s_grnd', 'inj_tot_f', 'inj_tot_m',
       'inj_tot_n', 'inj_tot_s', 'inj_tot_t', 'invest_agy', 'ntsb_docket',
       'ntsb_notf_from', 'ntsb_notf_date'

In [ ]:
# adding ev_type 
selected_columns = ['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'latitude', 'longitude', 'ev_nr_apt_id', 'wx_cond_basic','inj_tot_f', 'inj_tot_m', 'inj_tot_s' , 'inj_tot_n',  'ev_highest_injury']

df_events_og_replace_2 = df_events[selected_columns].copy()

In [ ]:
df_events_og_replace_2.info 

<bound method DataFrame.info of                 ev_id     ntsb_no ev_type            ev_date latitude  \
0      20080211X00175  DFW08RA039     ACC  01/10/08 00:00:00      NaN   
1      20080107X00026  SEA08LA057     ACC  01/01/08 00:00:00  381326N   
2      20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00  293022N   
3      20080107X00027  DFW08LA055     ACC  01/03/08 00:00:00  035321N   
4      20080115X00051  DEN08CA047     ACC  01/02/08 00:00:00  040276N   
...               ...         ...     ...                ...      ...   
25504  20230426107154  WPR23LA168     ACC  04/26/25 00:00:00      NaN   
25505  20230427107155  ERA23LA210     ACC  04/18/23 00:00:00      NaN   
25506  20230427107158  GAA23WA136     ACC  04/14/23 00:00:00      NaN   
25507  20230427107159  GAA23WA137     ACC  04/18/23 00:00:00      NaN   
25508  20230430107167  WPR23FA172     ACC  04/30/23 00:00:00      NaN   

      longitude ev_nr_apt_id wx_cond_basic  inj_tot_f  inj_tot_m  inj_tot_s  \
0           

In [ ]:
df_events_og_replace_2.columns 

Index(['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'latitude', 'longitude',
       'ev_nr_apt_id', 'wx_cond_basic', 'inj_tot_f', 'inj_tot_m', 'inj_tot_s',
       'inj_tot_n', 'ev_highest_injury'],
      dtype='object')

In [ ]:
df_events_og_replace_2['ev_type'].unique()

array(['ACC', 'INC'], dtype=object)

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_events_og_replace_2.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_events_og_replace_2.to_csv(f)

##Reading in and selecting tables from `engines.csv`

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving engines.csv to engines.csv


In [ ]:
df_engines = pd.read_csv('engines.csv')

In [ ]:
df_engines.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  eng_no eng_type                eng_mfgr  \
0      20080107X00026             1       1      REC        Textron Lycoming   
1      20080107X00026             2       1      REC        Textron Lycoming   
2      20080109X00036             1       1      REC                Lycoming   
3      20080107X00027             1       1       TP  Pratt & Whitney Canada   
4      20080115X00051             1       1      REC                Lycoming   
...               ...           ...     ...      ...                     ...   
23603  20230313106882             1       1       TS                   Rotax   
23604  20230313106884             1       1      REC                Lycoming   
23605  20230313106885             1       1      REC             Continental   
23606  20230313106889             1       1      REC        Lycoming Engines   
23607  20230324106947             1       1      REC                   Titan   

       

In [ ]:
df_engines.columns

Index(['ev_id', 'Aircraft_Key', 'eng_no', 'eng_type', 'eng_mfgr', 'eng_model',
       'power_units', 'hp_or_lbs', 'lchg_userid', 'lchg_date',
       'carb_fuel_injection', 'propeller_type', 'propeller_make',
       'propeller_model', 'eng_time_total', 'eng_time_last_insp',
       'eng_time_overhaul'],
      dtype='object')

Notice how there are more engine types than records/rows.
This is because there are accidents (and perhaps incidents as well) that involve more than one aircraft: hence, `'Aircraft_Key'`

In [ ]:
df_engines['eng_type'].unique

<bound method Series.unique of 0        REC
1        REC
2        REC
3         TP
4        REC
        ... 
23603     TS
23604    REC
23605    REC
23606    REC
23607    REC
Name: eng_type, Length: 23608, dtype: object>

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key','eng_type']

df_engines_og_replace = df_engines[selected_columns].copy()

In [ ]:
df_engines_og_replace.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key eng_type
0      20080107X00026             1      REC
1      20080107X00026             2      REC
2      20080109X00036             1      REC
3      20080107X00027             1       TP
4      20080115X00051             1      REC
...               ...           ...      ...
23603  20230313106882             1       TS
23604  20230313106884             1      REC
23605  20230313106885             1      REC
23606  20230313106889             1      REC
23607  20230324106947             1      REC

[23608 rows x 3 columns]>

In [ ]:
df_engines_og_replace.columns

Index(['ev_id', 'Aircraft_Key', 'eng_type'], dtype='object')

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_engines_og_replace.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_engines_og_replace.to_csv(f)

##Reading in and selecting columns from `events.csv`

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving events.csv to events.csv


In [ ]:
df_events = pd.read_csv('events.csv')

<ipython-input-9-3850d9eac6c9>:1: DtypeWarning: Columns (0,31,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df_events = pd.read_csv('events.csv')


In [ ]:
df_events.info

<bound method DataFrame.info of                 ev_id     ntsb_no ev_type            ev_date ev_dow  ev_time  \
0      20080211X00175  DFW08RA039     ACC  01/10/08 00:00:00     Th   1907.0   
1      20080107X00026  SEA08LA057     ACC  01/01/08 00:00:00     Tu   2230.0   
2      20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00     Tu   2200.0   
3      20080107X00027  DFW08LA055     ACC  01/03/08 00:00:00     Th    825.0   
4      20080115X00051  DEN08CA047     ACC  01/02/08 00:00:00     We   2230.0   
...               ...         ...     ...                ...    ...      ...   
25504  20230426107154  WPR23LA168     ACC  04/26/25 00:00:00     Sa    120.0   
25505  20230427107155  ERA23LA210     ACC  04/18/23 00:00:00     Tu   2310.0   
25506  20230427107158  GAA23WA136     ACC  04/14/23 00:00:00     Fr   1930.0   
25507  20230427107159  GAA23WA137     ACC  04/18/23 00:00:00     Tu   1002.0   
25508  20230430107167  WPR23FA172     ACC  04/30/23 00:00:00     Su    530.0   

      e

In [ ]:
df_events.columns

Index(['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'ev_dow', 'ev_time',
       'ev_tmzn', 'ev_city', 'ev_state', 'ev_country', 'ev_site_zipcode',
       'ev_year', 'ev_month', 'mid_air', 'on_ground_collision', 'latitude',
       'longitude', 'latlong_acq', 'apt_name', 'ev_nr_apt_id', 'ev_nr_apt_loc',
       'apt_dist', 'apt_dir', 'apt_elev', 'wx_brief_comp', 'wx_src_iic',
       'wx_obs_time', 'wx_obs_dir', 'wx_obs_fac_id', 'wx_obs_elev',
       'wx_obs_dist', 'wx_obs_tmzn', 'light_cond', 'sky_cond_nonceil',
       'sky_nonceil_ht', 'sky_ceil_ht', 'sky_cond_ceil', 'vis_rvr', 'vis_rvv',
       'vis_sm', 'wx_temp', 'wx_dew_pt', 'wind_dir_deg', 'wind_dir_ind',
       'wind_vel_kts', 'wind_vel_ind', 'gust_ind', 'gust_kts', 'altimeter',
       'wx_dens_alt', 'wx_int_precip', 'metar', 'ev_highest_injury',
       'inj_f_grnd', 'inj_m_grnd', 'inj_s_grnd', 'inj_tot_f', 'inj_tot_m',
       'inj_tot_n', 'inj_tot_s', 'inj_tot_t', 'invest_agy', 'ntsb_docket',
       'ntsb_notf_from', 'ntsb_notf_date'

In [ ]:
df_events['ev_date'].unique()

array(['01/10/08 00:00:00', '01/01/08 00:00:00', '01/03/08 00:00:00', ...,
       '04/23/23 00:00:00', '04/26/25 00:00:00', '04/30/23 00:00:00'],
      dtype=object)

In [ ]:
df_events['ev_date'].value_counts()

07/23/11 00:00:00    18
06/18/11 00:00:00    18
09/01/18 00:00:00    17
05/29/10 00:00:00    16
03/19/11 00:00:00    16
                     ..
11/01/21 00:00:00     1
11/15/18 00:00:00     1
03/20/13 00:00:00     1
11/01/18 00:00:00     1
04/30/23 00:00:00     1
Name: ev_date, Length: 5471, dtype: int64

**Creating a USA-only events dataframe.**

In [ ]:
df_events_usa = df_events[df_events['ev_country'] == 'USA']

**Comparing the length of `df_events_usa ` to `'df_events'` which includes international events.**
(Keep in mind events in which an American aircraft are rented for foreign trips. Recall the NTSB report about a Taiwan trip wherein the aircraft was transported by boat to Taiwanese waters and then crashed there.)

In [ ]:
len(df_events)

25509

In [ ]:
len(df_events_usa)

21219

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_events_usa.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_events_usa.to_csv(f)

Checking to see if this new dataset will have sufficient spread of events acrocss the years.
(Note: the 2025 typo from this record: WPR23LA168; 4/26/25; Nyssa, OR. We can probably just delete as it as most values missing.)

In [ ]:
df_events_usa['ev_year'].value_counts()

2008    1709
2011    1612
2009    1603
2012    1575
2010    1559
2018    1350
2016    1342
2017    1331
2014    1315
2015    1313
2013    1313
2019    1302
2022    1267
2021    1216
2020    1138
2023     273
2025       1
Name: ev_year, dtype: int64

**Creating a new events dataframe which includes columns from the NTSB dataset I think would be useful for our analysis.**

In [ ]:

selected_columns = ['ev_id', 'ntsb_no', 'apt_name','ev_city','ev_state','ev_country','ev_date', 'light_cond','mid_air', 'wx_cond_basic',
'wx_int_precip', 'wx_temp', 'inj_f_grnd', 'inj_m_grnd', 'inj_s_grnd', 'inj_tot_f', 'inj_tot_m',
       'inj_tot_n', 'inj_tot_s', 'inj_tot_t','ev_highest_injury','on_ground_collision']

df_events_edit =df_events[selected_columns].copy()

In [ ]:
df_events_edit.info

<bound method DataFrame.info of                 ev_id     ntsb_no               apt_name          ev_city  \
0      20080211X00175  DFW08RA039                    NaN  Pitt Meadow, BC   
1      20080107X00026  SEA08LA057     Schellville/Sonoma           Sonoma   
2      20080109X00036  DFW08CA054      HOUSTON-SOUTHWEST           Arcola   
3      20080107X00027  DFW08LA055             Wiley Post    Oklahoma City   
4      20080115X00051  DEN08CA047  Fort Collins Loveland         Loveland   
...               ...         ...                    ...              ...   
25504  20230426107154  WPR23LA168                    NaN            Nyssa   
25505  20230427107155  ERA23LA210                    NaN    St. Augustine   
25506  20230427107158  GAA23WA136                    NaN       Fort Smith   
25507  20230427107159  GAA23WA137                    NaN         Usa City   
25508  20230430107167  WPR23FA172                    NaN      Los Angeles   

      ev_state ev_country            ev_dat

In [ ]:
df_events_edit.columns

Index(['ev_id', 'ntsb_no', 'apt_name', 'ev_city', 'ev_state', 'ev_country',
       'ev_date', 'light_cond', 'mid_air', 'wx_cond_basic', 'wx_int_precip',
       'wx_temp', 'inj_f_grnd', 'inj_m_grnd', 'inj_s_grnd', 'inj_tot_f',
       'inj_tot_m', 'inj_tot_n', 'inj_tot_s', 'inj_tot_t', 'ev_highest_injury',
       'on_ground_collision'],
      dtype='object')

In [ ]:
#exporting csv to google drive
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/df_events_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_events_edit.to_csv(f)

##Reading in and selecting columns from `engines.csv`

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving engines.csv to engines.csv


In [ ]:
df_engines = pd.read_csv('engines.csv')

In [ ]:
df_engines.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  eng_no eng_type                eng_mfgr  \
0      20080107X00026             1       1      REC        Textron Lycoming   
1      20080107X00026             2       1      REC        Textron Lycoming   
2      20080109X00036             1       1      REC                Lycoming   
3      20080107X00027             1       1       TP  Pratt & Whitney Canada   
4      20080115X00051             1       1      REC                Lycoming   
...               ...           ...     ...      ...                     ...   
23603  20230313106882             1       1       TS                   Rotax   
23604  20230313106884             1       1      REC                Lycoming   
23605  20230313106885             1       1      REC             Continental   
23606  20230313106889             1       1      REC        Lycoming Engines   
23607  20230324106947             1       1      REC                   Titan   

       

In [ ]:
df_engines.columns 

Index(['ev_id', 'Aircraft_Key', 'eng_no', 'eng_type', 'eng_mfgr', 'eng_model',
       'power_units', 'hp_or_lbs', 'lchg_userid', 'lchg_date',
       'carb_fuel_injection', 'propeller_type', 'propeller_make',
       'propeller_model', 'eng_time_total', 'eng_time_last_insp',
       'eng_time_overhaul'],
      dtype='object')

**Creating a new engines dataframe which includes columns from the NTSB dataset I think would be useful for our analysis.**

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key', 'eng_no', 'eng_type','eng_mfgr','eng_model','eng_time_last_insp', 'eng_time_overhaul']

df_engines_edit =df_engines[selected_columns].copy()

In [ ]:
df_engines_edit.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  eng_no eng_type                eng_mfgr  \
0      20080107X00026             1       1      REC        Textron Lycoming   
1      20080107X00026             2       1      REC        Textron Lycoming   
2      20080109X00036             1       1      REC                Lycoming   
3      20080107X00027             1       1       TP  Pratt & Whitney Canada   
4      20080115X00051             1       1      REC                Lycoming   
...               ...           ...     ...      ...                     ...   
23603  20230313106882             1       1       TS                   Rotax   
23604  20230313106884             1       1      REC                Lycoming   
23605  20230313106885             1       1      REC             Continental   
23606  20230313106889             1       1      REC        Lycoming Engines   
23607  20230324106947             1       1      REC                   Titan   

       

In [ ]:
df_engines_edit.columns

Index(['ev_id', 'Aircraft_Key', 'eng_no', 'eng_type', 'eng_mfgr', 'eng_model',
       'eng_time_last_insp', 'eng_time_overhaul'],
      dtype='object')

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_engines_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_engines_edit.to_csv(f)

##Reading in and selecting columns from `events_sequence.csv`

Every event contains stages which happen in a sequence. This data is recorded in `events_sequence.csv.`

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving events_sequence.csv to events_sequence.csv


In [ ]:
df_events_sequence = pd.read_csv('events_sequence.csv')

In [ ]:
df_events_sequence.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
0      20080107X00026             1              1           550250   
1      20080107X00026             2              1           350250   
2      20080109X00036             1              1           551230   
3      20080109X00036             1              2           550300   
4      20080107X00027             1              1           153081   
...               ...           ...            ...              ...   
55618  20230426107154             1              1           300240   
55619  20230427107155             1              1           551090   
55620  20230427107158             1              1           550094   
55621  20230427107159             1              1           400342   
55622  20230430107167             1              1           990200   

                                  Occurrence_Description  phase_no  \
0                               Landing Midai

In [ ]:
df_events_sequence.columns

Index(['ev_id', 'Aircraft_Key', 'Occurrence_No', 'Occurrence_Code',
       'Occurrence_Description', 'phase_no', 'eventsoe_no', 'Defining_ev',
       'lchg_date', 'lchg_userid'],
      dtype='object')

**Creating a new events_sequence dataframe which includes columns from the NTSB dataset I think would be useful for our analysis.**

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key','Occurrence_No','Occurrence_Code','Occurrence_Description','phase_no','eventsoe_no', 'Defining_ev']

df_events_sequence_edit = df_events_sequence[selected_columns].copy()

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_events_sequence_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_events_sequence_edit.to_csv(f)

Digging deeper into the significance of `occurence code` vs  `phase code` and where the modifier comes from.

NTSB's data dictionary says: "Phases and events cited in an accident `events_sequence `timeline are entered in chronological order. The `occurrence_no` variable indicates the order of event occurrence starting with `occurrence_no` = 1."

In [ ]:
# One event could involve up to 15 stages!
df_events_sequence['Occurrence_No'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 16, 14, 15])

In [ ]:
# Thankfully, only one event from 2008 - 2023 involved 15 stages.
# The majority involve only 1 - 2 stages.
df_events_sequence['Occurrence_No'].value_counts()

1     23786
2     16083
3      9590
4      4081
5      1440
6       439
7       121
8        49
9        17
10        6
11        4
12        2
13        2
16        1
14        1
15        1
Name: Occurrence_No, dtype: int64

In reseraching `'phase_no'` as it corresponds to the phase of flight (see data dictionary), I have learned that the `'Occurrence_Code'`column is a compound code that combines the `'phase_no'` and `'eventsoe_no'` codes. 

In [ ]:
df_events_sequence['Occurrence_Code'].unique()

array([550250, 350250, 551230, ..., 800341, 601244, 990091])

In [ ]:
df_events_sequence['Occurrence_Code'].value_counts()

650470    2398
552230    1763
552300    1648
600440    1637
552470    1502
          ... 
509281       1
990040       1
650192       1
253336       1
990091       1
Name: Occurrence_Code, Length: 1528, dtype: int64

In [ ]:
df_events_sequence['phase_no'].unique()

array([550, 350, 551, 153, 600, 552, 650, 500, 402, 450, 506, 200, 300,
       508, 502, 509, 501, 253, 251, 100, 401, 404, 452, 700, 250, 504,
       451, 301, 990, 800, 601, 507, 400, 252, 152, 453, 150, 505, 405,
       553, 154, 201, 202, 151, 503, 403, 203, 750])

In [ ]:
df_events_sequence['phase_no'].value_counts()

552    7889
550    6716
300    4748
551    4636
350    3636
402    3201
600    3137
650    2554
452    2436
400    2065
450    1971
508    1351
500    1286
100    1260
301     786
509     769
401     654
404     627
990     558
601     514
700     495
553     481
453     442
250     417
507     350
253     340
506     329
251     272
502     258
451     238
153     200
800     184
152     154
501     104
504      98
252      79
150      68
403      63
505      52
750      51
200      38
151      38
503      28
201      16
154      14
405       7
202       7
203       6
Name: phase_no, dtype: int64

The NTSB data dictionary indicates all of thes evalues should be 3 digits but some of these are two digits. Need to investigate these two digit records...

In [ ]:
df_events_sequence['eventsoe_no'].unique()

array([250, 230, 300,  81, 240, 470, 341, 330, 241, 342, 440,  96,  92,
       190, 441, 400, 192, 270, 380, 200,  94, 334,  60, 337,  97, 120,
       490, 130, 360, 338,  90, 402, 900,  40, 340, 332, 191, 170,  93,
       282, 410, 430, 220, 401, 193, 362, 333, 150,  95, 901,  30, 110,
       210, 242,  50,   0, 370, 140, 390, 361, 600, 281, 244,  20, 320,
       232, 160, 310, 480,  80,  70, 100, 343, 500, 260,  10, 180,  91,
       420,  82, 510, 450, 350, 231, 271, 331, 460, 194, 990, 336, 245,
       284, 335, 243, 850, 280])

In [ ]:
df_events_sequence['eventsoe_no'].value_counts()

470    9596
240    4241
230    3798
341    3449
300    3023
       ... 
280       8
194       7
335       6
410       6
243       1
Name: eventsoe_no, Length: 96, dtype: int64

##Confirming that the `'eventsoe_no'` codes < 3 digits are missing zeroes.

In [ ]:
# confirming missing zeros list {000: 'Unknown or undetermined'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 0].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
488   20080502X00582             1              2           650000   
1440  20081003X16301             1              1           400000   
1576  20081004X21118             1              1           300000   

                            Occurrence_Description  phase_no  eventsoe_no  \
488   Uncontrolled descent Unknown or undetermined       650            0   
1440               Enroute Unknown or undetermined       400            0   
1576               Takeoff Unknown or undetermined       300            0   

      Defining_ev          lchg_date  lchg_userid  
488             0  09/25/20 18:04:02          NaN  
1440            1  09/25/20 18:07:50          NaN  
1576            1  11/03/20 20:28:02          NaN

In [ ]:
# confirming missing zeros list {010: 'Aircraft loading event'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 10].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
2198  20080820X01266             1              1           100010   
5092  20090506X83403             1              2           100010   
5384  20090601X22459             1              1           100010   

                      Occurrence_Description  phase_no  eventsoe_no  \
2198  Prior to flight Aircraft loading event       100           10   
5092  Prior to flight Aircraft loading event       100           10   
5384  Prior to flight Aircraft loading event       100           10   

      Defining_ev          lchg_date  lchg_userid  
2198            0  12/16/21 18:21:36          NaN  
5092            0  09/25/20 18:00:53          NaN  
5384            0  09/25/20 17:59:24          NaN

In [ ]:
# confirming missing zeros list {020: 'Aircraft servicing event'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 20].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
1106  20080609X00813             1              1           100020   
2462  20080915X01461             1              1           100020   
3064  20080925X01527             1              2           100020   

                        Occurrence_Description  phase_no  eventsoe_no  \
1106  Prior to flight Aircraft servicing event       100           20   
2462  Prior to flight Aircraft servicing event       100           20   
3064  Prior to flight Aircraft servicing event       100           20   

      Defining_ev          lchg_date  lchg_userid  
1106            0  09/25/20 18:04:46          NaN  
2462            0  09/25/20 18:04:46          NaN  
3064            0  09/25/20 18:06:16          NaN

In [ ]:
# confirming {030: 'Preflight or dispatch event'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 30].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
374  20080320X00341             1              1           100030   
379  20080222X00232             1              1           100030   
418  20080422X00530             1              1           100030   

                          Occurrence_Description  phase_no  eventsoe_no  \
374  Prior to flight Preflight or dispatch event       100           30   
379  Prior to flight Preflight or dispatch event       100           30   
418  Prior to flight Preflight or dispatch event       100           30   

     Defining_ev          lchg_date  lchg_userid  
374            0  09/25/20 18:07:03          NaN  
379            0  09/25/20 18:06:16          NaN  
418            0  09/25/20 18:07:03          NaN

In [ ]:
# confirming  {040: 'Aircraft maintenance event'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 40].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
111  20080210X00161             1              1           100040   
172  20080211X00174             1              1           100040   
268  20080221X00223             1              1           100040   

                         Occurrence_Description  phase_no  eventsoe_no  \
111  Prior to flight Aircraft maintenance event       100           40   
172  Prior to flight Aircraft maintenance event       100           40   
268  Prior to flight Aircraft maintenance event       100           40   

     Defining_ev          lchg_date  lchg_userid  
111            0  09/25/20 18:07:03          NaN  
172            0  09/25/20 18:06:16          NaN  
268            0  09/25/20 18:05:31          NaN

In [ ]:
# confiming missing zeroes list  {050: 'Aircraft inspection event'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 50].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
476   20080523X00714             1              2           100050   
1770  20080808X01189             1              1           100050   
2001  20080810X01197             1              1           100050   

                         Occurrence_Description  phase_no  eventsoe_no  \
476   Prior to flight Aircraft inspection event       100           50   
1770  Prior to flight Aircraft inspection event       100           50   
2001  Prior to flight Aircraft inspection event       100           50   

      Defining_ev          lchg_date  lchg_userid  
476             0  09/25/20 18:07:03          NaN  
1770            0  09/25/20 18:06:16          NaN  
2001            0  09/25/20 18:07:03          NaN

In [ ]:
# confirming missing zeroes list  {060: 'Attempted remediation/recovery'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 60].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
55   20080129X00119             1              3           350060   
815  20080404X00426             1              2           552060   
892  20080410X00449             1              2           550060   

                                Occurrence_Description  phase_no  eventsoe_no  \
55        Initial climb Attempted remediation/recovery       350           60   
815  Landing-landing roll Attempted remediation/rec...       552           60   
892             Landing Attempted remediation/recovery       550           60   

     Defining_ev          lchg_date  lchg_userid  
55             0  09/25/20 18:04:46          NaN  
815            0  09/25/20 18:04:46          NaN  
892            0  09/25/20 18:06:16          NaN

In [ ]:
# confirming missing zeroes list {070: 'Airport occurrence'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 70].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
1744  20080709X00995             1              1           253070   
1745  20080709X00995             2              1           300070   
1860  20080714X01033             1              1           252070   

                             Occurrence_Description  phase_no  eventsoe_no  \
1744            Taxi-from runway Airport occurrence       253           70   
1745                     Takeoff Airport occurrence       300           70   
1860  Taxi-into takeoff position Airport occurrence       252           70   

      Defining_ev          lchg_date  lchg_userid  
1744            1  09/25/20 18:06:16          NaN  
1745            1  09/25/20 18:06:16          NaN  
1860            1  09/25/20 18:06:16          NaN

In [ ]:
# confirming missing zeroes list {080: 'Ground handling event'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 80].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
1699  20080720X01081             1              1           200080   
1700  20080720X01081             2              1           150080   
2400  20080822X01296             1              1           153080   

                                 Occurrence_Description  phase_no  \
1699              Pushback/towing Ground handling event       200   
1700                     Standing Ground handling event       150   
2400  Standing-engine(s) operating Ground handling e...       153   

      eventsoe_no  Defining_ev          lchg_date  lchg_userid  
1699           80            1  09/25/20 18:07:03          NaN  
1700           80            1  09/25/20 18:07:03          NaN  
2400           80            1  09/25/20 18:05:31          NaN

In [ ]:
# confirming missing zeroes list {081: 'AC/prop/rotor contact w person'}

df_events_sequence[df_events_sequence['eventsoe_no'] == 81].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
4     20080107X00027             1              1           153081   
2266  20080808X01192             1              1           153081   
3271  20081014X22933             1              1           153081   

                                 Occurrence_Description  phase_no  \
4     Standing-engine(s) operating AC/prop/rotor con...       153   
2266  Standing-engine(s) operating AC/prop/rotor con...       153   
3271  Standing-engine(s) operating AC/prop/rotor con...       153   

      eventsoe_no  Defining_ev          lchg_date  lchg_userid  
4              81            1  09/25/20 18:04:02          NaN  
2266           81            1  09/25/20 18:06:16          NaN  
3271           81            1  09/25/20 18:07:03          NaN

In [ ]:
# confirming missing zeroes list {082: 'Prop/jet/rotor blast/suction'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 82].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
2615  20081003X17545             1              1           251082   
4306  20090223X64314             1              1           250082   
6733  20090825X64630             1              1           250082   

                           Occurrence_Description  phase_no  eventsoe_no  \
2615  Taxi-to runway Prop/jet/rotor blast/suction       251           82   
4306            Taxi Prop/jet/rotor blast/suction       250           82   
6733            Taxi Prop/jet/rotor blast/suction       250           82   

      Defining_ev          lchg_date  lchg_userid  
2615            1  09/25/20 18:05:31          NaN  
4306            1  09/25/20 18:02:29          NaN  
6733            1  09/25/20 17:59:24          NaN

In [ ]:
# confirming missing zeroes list  {090: 'Abnormal runway contact'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 90].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
78   20080220X00218             1              5           550090   
84   20080312X00302             1              1           551090   
180  20080226X00235             1              1           551090   

                              Occurrence_Description  phase_no  eventsoe_no  \
78                   Landing Abnormal runway contact       550           90   
84   Landing-flare/touchdown Abnormal runway contact       551           90   
180  Landing-flare/touchdown Abnormal runway contact       551           90   

     Defining_ev          lchg_date  lchg_userid  
78             0  09/25/20 18:06:16          NaN  
84             0  09/25/20 18:05:31          NaN  
180            0  09/25/20 18:06:16          NaN

In [ ]:
# confirming missing zeroes list {091: 'Tailstrike'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 91].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
2566  20081003X17330             1              2           550091   
3420  20081027X75039             1              1           551091   
3738  20081216X82956             1              1           551091   

                  Occurrence_Description  phase_no  eventsoe_no  Defining_ev  \
2566                  Landing Tailstrike       550           91            1   
3420  Landing-flare/touchdown Tailstrike       551           91            1   
3738  Landing-flare/touchdown Tailstrike       551           91            0   

              lchg_date  lchg_userid  
2566  09/25/20 18:04:02          NaN  
3420  09/25/20 18:04:46          NaN  
3738  11/03/20 20:28:45          NaN

In [ ]:
# confirming missing zeroes list {092: 'Hard landing'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 92].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
20  20080210X00166             1              1           551092   
52  20080204X00131             1              1           551092   
59  20080129X00117             1              2           551092   

                  Occurrence_Description  phase_no  eventsoe_no  Defining_ev  \
20  Landing-flare/touchdown Hard landing       551           92            1   
52  Landing-flare/touchdown Hard landing       551           92            1   
59  Landing-flare/touchdown Hard landing       551           92            0   

            lchg_date  lchg_userid  
20  09/25/20 18:05:31          NaN  
52  09/25/20 18:06:16          NaN  
59  09/25/20 18:04:46          NaN

In [ ]:
# confirming missing zeroes list {093: 'Dragged wing/rotor/float/other'}
 df_events_sequence[df_events_sequence['eventsoe_no'] == 93].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
139   20080207X00148             1              1           551093   
1022  20080604X00789             1              2           550093   
1080  20080603X00776             1              2           550093   

                                 Occurrence_Description  phase_no  \
139   Landing-flare/touchdown Dragged wing/rotor/flo...       551   
1022             Landing Dragged wing/rotor/float/other       550   
1080             Landing Dragged wing/rotor/float/other       550   

      eventsoe_no  Defining_ev          lchg_date  lchg_userid  
139            93            1  09/25/20 18:04:02          NaN  
1022           93            0  09/25/20 18:06:16          NaN  
1080           93            0  09/25/20 18:04:02          NaN

In [ ]:
 # confirming missing zeroes list {094: 'Landing gear collapse'}
 df_events_sequence[df_events_sequence['eventsoe_no'] == 94].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
51   20080213X00180             1              1           552094   
187  20080211X00168             1              2           552094   
194  20080305X00269             1              2           550094   

                         Occurrence_Description  phase_no  eventsoe_no  \
51   Landing-landing roll Landing gear collapse       552           94   
187  Landing-landing roll Landing gear collapse       552           94   
194               Landing Landing gear collapse       550           94   

     Defining_ev          lchg_date  lchg_userid  
51             1  09/25/20 18:07:03          NaN  
187            0  09/25/20 18:05:31          NaN  
194            0  09/25/20 18:06:16          NaN

In [ ]:
 # confirming missing zeroes list { 095: 'Landing gear not configured'}
 df_events_sequence[df_events_sequence['eventsoe_no'] == 95].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
308  20080430X00565             1              1           552095   
596  20080529X00748             1              1           550095   
679  20080317X00321             1              2           550095   

                               Occurrence_Description  phase_no  eventsoe_no  \
308  Landing-landing roll Landing gear not configured       552           95   
596               Landing Landing gear not configured       550           95   
679               Landing Landing gear not configured       550           95   

     Defining_ev          lchg_date  lchg_userid  
308            1  09/25/20 18:07:03          NaN  
596            1  09/25/20 18:06:16          NaN  
679            0  09/25/20 18:04:02          NaN

In [ ]:
# confirming missing zeroes list {096: 'Nose over/nose down'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 96].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
19  20080220X00212             1              2           552096   
29  20080219X00203             1              3           550096   
43  20080219X00204             1              1           300096   

                      Occurrence_Description  phase_no  eventsoe_no  \
19  Landing-landing roll Nose over/nose down       552           96   
29               Landing Nose over/nose down       550           96   
43               Takeoff Nose over/nose down       300           96   

    Defining_ev          lchg_date  lchg_userid  
19            0  09/25/20 18:06:16          NaN  
29            0  05/17/22 13:26:42          NaN  
43            1  09/25/20 18:04:02          NaN

In [ ]:
# confirming missing zeroes list  { 097: 'Roll over'}
df_events_sequence[df_events_sequence['eventsoe_no'] == 97].head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
60   20080129X00117             1              3           551097   
73   20080215X00202             1              4           550097   
333  20080430X00566             1              3           550097   

                Occurrence_Description  phase_no  eventsoe_no  Defining_ev  \
60   Landing-flare/touchdown Roll over       551           97            0   
73                   Landing Roll over       550           97            1   
333                  Landing Roll over       550           97            0   

             lchg_date  lchg_userid  
60   09/25/20 18:04:46          NaN  
73   09/25/20 18:04:02          NaN  
333  09/25/20 18:07:03          NaN

In [ ]:
  missing_zeros_list = [0, 10, 20, 30, 40, 50, 60, 70, 80, 81, 82, 90, 91, 92, 93, 94, 95, 96, 97]

##Now that we have confirmed these < 3 digit codes in th 'evensoe_no' column are merely missing zeroes, standardize the format by adding the missing zeroes

In [ ]:
# Convert 'eventsoe_no' to string 
df_events_sequence_str_copy['eventsoe_no'] = df_events_sequence_str_copy['eventsoe_no'].astype(str)

# Add leading zeroes
df_events_sequence_str_copy['eventsoe_no'] = df_events_sequence_str_copy['eventsoe_no'].str.zfill(3)


In [ ]:
# sanity check
df_events_sequence_str_copy['eventsoe_no'].unique() 

array(['250', '230', '300', '081', '240', '470', '341', '330', '241',
       '342', '440', '096', '092', '190', '441', '400', '192', '270',
       '380', '200', '094', '334', '060', '337', '097', '120', '490',
       '130', '360', '338', '090', '402', '900', '040', '340', '332',
       '191', '170', '093', '282', '410', '430', '220', '401', '193',
       '362', '333', '150', '095', '901', '030', '110', '210', '242',
       '050', '000', '370', '140', '390', '361', '600', '281', '244',
       '020', '320', '232', '160', '310', '480', '080', '070', '100',
       '343', '500', '260', '010', '180', '091', '420', '082', '510',
       '450', '350', '231', '271', '331', '460', '194', '990', '336',
       '245', '284', '335', '243', '850', '280'], dtype=object)

Attempting to make a dictionary with integers for keys led to an error becuase of the `'010'` code. Therefore, I have to make these strings in order to create my dictionary.

This seems like a good idea anyhow as the original dataset had this as "char" aka "strings".
("char" stands for a sequence of characters. In SQL and database terminology, a "char" field usually refers to a field that holds a fixed number of characters)


In [ ]:
# create events_sequence_dict 

event_sequence_dict = {
  '000': 'Unknown or undetermined',
  '010': 'Aircraft loading event',
  '020': 'Aircraft servicing event',
  '030': 'Preflight or dispatch event',
  '040': 'Aircraft maintenance event',
  '050': 'Aircraft inspection event',
  '060': 'Attempted remediation/recovery',
  '070': 'Airport occurrence',
  '080': 'Ground handling event',
  '081': 'AC/prop/rotor contact w person',
  '082': 'Prop/jet/rotor blast/suction',
  '090': 'Abnormal runway contact',
  '091': 'Tailstrike',
  '092': 'Hard landing',
  '093': 'Dragged wing/rotor/float/other',
  '094': 'Landing gear collapse',
  '095': 'Landing gear not configured',
  '096': 'Nose over/nose down',
  '097': 'Roll over',
  '100': 'Air traffic event',
  '110': 'Cabin safety event',
  '120': 'Control flight into terr/obj',
  '130': 'Emergency descent initiated',
  '140': 'Engine shutdown',
  '150': 'Fire/smoke (non-impact)',
  '160': 'Explosion (non-impact)',
  '170': 'Fire/smoke (post-impact)',
  '180': 'Explosion (post-impact)',
  '190': 'Fuel related',
  '191': 'Fuel starvation',
  '192': 'Fuel exhaustion',
  '193': 'Fuel contamination',
  '194': 'Wrong fuel',
  '200': 'Ground collision',
  '210': 'Icing encounter',
  '220': 'Low altitude operations',
  '230': 'Loss of control on ground',
  '231': 'Dynamic Rollover',
  '232': 'Ground resonance',
  '240': 'Loss of control in flight',
  '241': 'Aerodynamic stall/spin',
  '242': 'Loss of tail rotor effectiveness',
  '243': 'Retreating blade stall',
  '244': 'Settling with power/vortex ring state',
  '245': 'Mast bumping',
  '250': 'Midair collision',
  '260': 'Near midair collision',
  '270': 'Abrupt maneuver',
  '271': 'Inflight upset',
  '280': 'Course deviation',
  '290': 'Altitude deviation',
  '300': 'Runway excursion',
  '310': 'Runway incursion animal',
  '320': 'Runway incursion veh/AC/person',
  '330': 'Sys/Comp malf/fail (non-power)',
  '331': 'Pressure/environ sys malf/fail',
  '332': 'Electrical system malf/failure',
  '333': 'Flight control sys malf/fail',
  '334': 'Flight instrument malf/fail',
  '335': 'Nav system malfunction/failure',
  '336': 'Comm system malf/failure',
  '337': 'Aircraft structural failure',
  '338': 'Part(s) separation from AC',
  '340': 'Powerplant sys/comp malf/fail',
  '341': 'Loss of engine power (total)',
  '342': 'Loss of engine power (partial)',
  '343': 'Uncontained engine failure',
  '350': 'Security/criminal event',
  '360': 'Turbulence encounter',
  '361': 'Aircraft wake turb encounter',
  '362': 'Clear air turbulence encounter',
  '370': 'Landing area undershoot',
  '380': 'Landing area overshoot',
  '390': 'Windshear or thunderstorm',
  '400': 'Other weather encounter',
  '401': 'VFR encounter with IMC',
  '402': 'Loss of visual reference',
  '410': 'Terrain avoidance alert',
  '420': 'Collision avoidance alert',
  '430': 'Stall warn/stick-shaker/pusher',
  '440': 'Off-field or emergency landing',
  '441': 'Ditching',
  '450': 'Hazardous material leak/spill',
  '460': 'Evacuation',
  '470': 'Collision with terr/obj (non-CFIT)',
  '480': 'External load event (Rotorcraft)',
  '490': 'Collision during takeoff/land',
  '500': 'Loss of lift',
  '510': 'Glider tow event',
  '600': 'Simulated/training event',
  '900': 'Miscellaneous/other',
  '901': 'Birdstrike',
  '990': 'Missing aircraft'

} 


Now I can map the `'eventsoe_no'` column with my dictionary. Remember, I am creating an `'occurence'` column to represent the data that corresponds with the codes in `'eventsoe_no'`.

This column will give us more granual information concerning the events that transpired during the accident or incident. The distinction between accident and incident is important, hence 'occurrence' as an umbrella term.

`'Occurence_Description'` contains a combination of the `'phase_no`' and the `'eventsoe_no'` meanings. I am parsing the data this way as I believe it will make it more usable for our analysis

In [ ]:
#creating Occurrence column by mapping the codes in the eventsoe_no column with my dictionary
# NaN values will be replaced with 'Unknown Occurrence'
df_events_sequence_str_copy['Occurrence'] = df_events_sequence_str_copy['eventsoe_no'].map(event_sequence_dict).fillna('Unknown Occurrence')


In [ ]:
# Let's preview the work!
df_events_sequence_str_copy.head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
0  20080107X00026             1              1           550250   
1  20080107X00026             2              1           350250   
2  20080109X00036             1              1           551230   

                              Occurrence_Description  phase_no eventsoe_no  \
0                           Landing Midair collision       550         250   
1                     Initial climb Midair collision       350         250   
2  Landing-flare/touchdown Loss of control on ground       551         230   

   Defining_ev          lchg_date  lchg_userid broad phase of flight  \
0            1  09/25/20 18:05:31          NaN               Landing   
1            1  09/25/20 18:05:31          NaN         Initial Climb   
2            1  09/25/20 18:05:31          NaN               Landing   

   broad_phase_no                 Occurrence  
0              55           Midair collision  
1              35           Midair collision  
2              55  Loss of control on ground

In [ ]:
df_events_sequence_str_copy.tail(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
55620  20230427107158             1              1           550094   
55621  20230427107159             1              1           400342   
55622  20230430107167             1              1           990200   

                       Occurrence_Description  phase_no eventsoe_no  \
55620           Landing Landing gear collapse       550         094   
55621  Enroute Loss of engine power (partial)       400         342   
55622                Unknown Ground collision       990         200   

       Defining_ev          lchg_date  lchg_userid broad phase of flight  \
55620            1  04/27/23 16:05:58          NaN               Landing   
55621            1  04/27/23 16:11:51          NaN               Enroute   
55622            1  04/30/23 12:51:33          NaN               Unknown   

       broad_phase_no                      Occurrence  
55620              55           Landing gear collapse  
55621              40  Loss of engine power (partial)  
55622              99                Ground collision

I tried to check the length of occurence codes before creating my `broad phase of flight` column, but I can't do it like this because the data type is int64! This code returns an error:



```
df_events_sequence['Occurrence_Code_length'] = df_events_sequence['Occurrence_Code'].str.len()
```

So I will need to turn occurrence code into a string.


In [ ]:
# making a copy of the dataframe so I can turn occurence code into a string
df_events_sequence_str_copy = df_events_sequence.copy()

In [ ]:
#turning occurence code into a string
df_events_sequence_str_copy['Occurrence_Code'] = df_events_sequence_str_copy['Occurrence_Code'].astype(str)


In [ ]:
# checking the length now that we have our string version
df_events_sequence_str_copy['Occurrence_Code_length'] = df_events_sequence_str_copy['Occurrence_Code'].str.len()
print(df_events_sequence_str_copy['Occurrence_Code_length'].unique())


[6]


In [ ]:
#extracting 'phase_no' and 'eventsoe_no' from our new string, which we have confirmed is always 6 char/digits long
df_events_sequence_str_copy['phase no'] = df_events_sequence_str_copy['Occurrence_Code'].str[:3].astype(int)
df_events_sequence_str_copy['eventsoe_no'] = df_events_sequence_str_copy['Occurrence_Code'].str[3:].astype(int)


In [ ]:
df_events_sequence_str_copy.head(3)

ev_id  Aircraft_Key  Occurrence_No Occurrence_Code  \
0  20080107X00026             1              1          550250   
1  20080107X00026             2              1          350250   
2  20080109X00036             1              1          551230   

                              Occurrence_Description  phase_no  eventsoe_no  \
0                           Landing Midair collision       550          250   
1                     Initial climb Midair collision       350          250   
2  Landing-flare/touchdown Loss of control on ground       551          230   

   Defining_ev          lchg_date  lchg_userid  Occurrence_Code_length  \
0            1  09/25/20 18:05:31          NaN                       6   
1            1  09/25/20 18:05:31          NaN                       6   
2            1  09/25/20 18:05:31          NaN                       6   

   phase no  
0       550  
1       350  
2       551

Checking something before I create my phase_dict as there is a duplicate key in the NTSB data dictionary:

Both 242 and 401 have the same value: `'VFR encounter with IMC'` This makes no sense; one must be a user error and I need to figure out which

Looking at the first record for example: since `phase_no` 402 == `'Enroute-cruise'`, it is clear that 242 should be updated to `'Loss of tail rotor effectiveness'`

In [ ]:

df_events_sequence_str_copy.loc[df_events_sequence_str_copy['eventsoe_no'] == 242]


ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
429    20080417X00503             1              2           402242   
1202   20080529X00752             1              2           550242   
1816   20080806X01165             1              1           453242   
1955   20090211X92091             1              2           450242   
1994   20080807X01175             1              1           453242   
...               ...           ...            ...              ...   
51985  20210915103863             1              2           453242   
52226  20211006104054             1              1           400242   
53782  20220621105297             1              1           402242   
54022  20220719105522             1              1           550242   
54609  20221003106044             1              1           450242   

                                  Occurrence_Description  phase_no  \
429      Enroute-cruise Loss of tail rotor effectiveness       402   
1202            Landing Loss of tail rotor effectiveness       550   
1816   Maneuvering-hover Loss of tail rotor effective...       453   
1955        Maneuvering Loss of tail rotor effectiveness       450   
1994   Maneuvering-hover Loss of tail rotor effective...       453   
...                                                  ...       ...   
51985  Maneuvering-hover Loss of tail rotor effective...       453   
52226           Enroute Loss of tail rotor effectiveness       400   
53782    Enroute-cruise Loss of tail rotor effectiveness       402   
54022           Landing Loss of tail rotor effectiveness       550   
54609       Maneuvering Loss of tail rotor effectiveness       450   

       eventsoe_no  Defining_ev          lchg_date  lchg_userid  
429            242            0  06/07/22 13:24:23          NaN  
1202           242            1  09/25/20 18:06:16          NaN  
1816           242            1  09/25/20 18:06:16          NaN  
1955           242            1  11/03/20 20:28:03          NaN  
1994           242            1  09/25/20 18:07:03          NaN  
...            ...          ...                ...          ...  
51985          242            1  05/04/22 16:05:19          NaN  
52226          242            1  10/06/21 03:17:14          NaN  
53782          242            1  07/01/22 18:00:11          NaN  
54022          242            1  09/22/22 18:00:10          NaN  
54609          242            1  10/14/22 18:00:02          NaN  

[93 rows x 10 columns]

Confirming 401 == `'VFR encounter with IMC'` and it does! This makes more sense as the codes directly proceeding 401 concern the weather, and the codes preceding 242 concern the tail rotor.

In [ ]:
df_events_sequence_str_copy.loc[df_events_sequence_str_copy['eventsoe_no'] == 401]

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
188    20080222X00227             1              1           450401   
235    20080219X00209             1              1           400401   
381    20080222X00232             1              3           452401   
800    20080331X00400             1              1           402401   
842    20080407X00434             1              1           402401   
...               ...           ...            ...              ...   
53969  20220716105484             1              1           350401   
54088  20220725105567             1              1           402401   
55397  20230307106842             1              2           350401   
55489  20230325106955             1              2           650401   
55490  20230326106956             1              2           452401   

                                  Occurrence_Description  phase_no  \
188                   Maneuvering VFR encounter with IMC       450   
235                       Enroute VFR encounter with IMC       400   
381    Maneuvering-low-alt flying VFR encounter with IMC       452   
800                Enroute-cruise VFR encounter with IMC       402   
842                Enroute-cruise VFR encounter with IMC       402   
...                                                  ...       ...   
53969               Initial climb VFR encounter with IMC       350   
54088              Enroute-cruise VFR encounter with IMC       402   
55397               Initial climb VFR encounter with IMC       350   
55489        Uncontrolled descent VFR encounter with IMC       650   
55490  Maneuvering-low-alt flying VFR encounter with IMC       452   

       eventsoe_no  Defining_ev          lchg_date  lchg_userid  
188            401            1  09/25/20 18:04:46          NaN  
235            401            1  09/25/20 18:05:31          NaN  
381            401            1  09/25/20 18:06:16          NaN  
800            401            0  09/25/20 18:05:31          NaN  
842            401            0  09/25/20 18:04:02          NaN  
...            ...          ...                ...          ...  
53969          401            1  07/22/22 18:00:04          NaN  
54088          401            1  08/18/22 18:00:02          NaN  
55397          401            1  03/15/23 18:00:04          NaN  
55489          401            0  04/11/23 18:00:03          NaN  
55490          401            1  04/12/23 21:08:45          NaN  

[335 rows x 10 columns]

in the process of creating the previous dictionary and confirming in the documentation, a `broad phase of flight` column could be created by only referencing the first two digits of the `'phase_no'`.

In [ ]:
# creating a broad phase of flight dictionary to make my new broad phase of flight column

broad_phase_dict = {
    10: 'Prior to flight',
    15: 'Standing',
    20: 'Pushback/Towing',
    25: 'Taxi',
    35: 'Initial Climb',
    40: 'Enroute',
    45: 'Maneuvering',
    50: 'Approach',
    55: 'Landing',
    60: 'Emergency Descent',
    65: 'Uncontrolled Descent',
    70: 'Post-Impact',
    75: 'After Landing',
    80: 'Other',
    99: 'Unknown',

}



In [ ]:
# Extract the first two digits of 'phase_no' in order to create this new broad phase of flight column
df_events_sequence_str_copy['broad_phase_no'] = df_events_sequence_str_copy['phase_no'] // 10

# Create a new 'broad phase of flight' column by mapping 'broad_phase_no' with the dictionary
df_events_sequence_str_copy['broad phase of flight'] = df_events_sequence_str_copy['broad_phase_no'].map(broad_phase_dict).fillna('Unknown broad phase')


In [ ]:
# let's preview the work!
df_events_sequence_str_copy.head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
0  20080107X00026             1              1           550250   
1  20080107X00026             2              1           350250   
2  20080109X00036             1              1           551230   

                              Occurrence_Description  phase_no  eventsoe_no  \
0                           Landing Midair collision       550          250   
1                     Initial climb Midair collision       350          250   
2  Landing-flare/touchdown Loss of control on ground       551          230   

   Defining_ev          lchg_date  lchg_userid broad phase of flight  \
0            1  09/25/20 18:05:31          NaN               Landing   
1            1  09/25/20 18:05:31          NaN         Initial Climb   
2            1  09/25/20 18:05:31          NaN               Landing   

   broad_phase_no  
0              55  
1              35  
2              55

In [ ]:
# looks like it worked!
df_events_sequence_str_copy.tail(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
55620  20230427107158             1              1           550094   
55621  20230427107159             1              1           400342   
55622  20230430107167             1              1           990200   

                       Occurrence_Description  phase_no  eventsoe_no  \
55620           Landing Landing gear collapse       550           94   
55621  Enroute Loss of engine power (partial)       400          342   
55622                Unknown Ground collision       990          200   

       Defining_ev          lchg_date  lchg_userid broad phase of flight  \
55620            1  04/27/23 16:05:58          NaN               Landing   
55621            1  04/27/23 16:11:51          NaN               Enroute   
55622            1  04/30/23 12:51:33          NaN               Unknown   

       broad_phase_no  
55620              55  
55621              40  
55622              99

Creating specific phase dictionary in order to create the the specific phase of flight column. This is using only the `'phase_no'`. Also, we are using strings and not integers to keep consistent with dataset origin.
Creating these new dictionaries will allow for more parsing of data as well as being a cleaner method than attempting to split the `'Occurrence_Description'` column

In [ ]:
# creating specific phase dictionary in order to create the the specific phase of flight column

specific_phase_dict = {
    '100': 'Prior to flight',
    '150': 'Standing',
    '151': 'Standing-Engine(s) Not Oper',
    '152': 'Standing-Engine(s) Start-up',
    '153': 'Standing-Engine(s) Operating',
    '154': 'Standing-Engine(s) Shutdown',
    '200': 'Pushback/Towing',
    '201': 'Pushback/Tow-Engine Not Oper',
    '202': 'Pushback/Tow-Engine Start-up',
    '203': 'Pushback/Tow-Engine Oper',
    '204': 'Pushback/Tow-Engine Shutdown',
    '250': 'Taxi',
    '251': 'Taxi-to Runway',
    '252': 'Taxi-into Takeoff Position',
    '253': 'Taxi-from Runway',
    '300': 'Takeoff', 
    '301': 'Takeoff-Rejected Takeoff',
    '350': 'Initial Climb',
    '400': 'Enroute',
    '401': 'Enroute-Climb to cruise',
    '402': 'Enroute-Cruise',
    '403': 'Enroute-Change of cruise level',
    '404': 'Enroute-Descent',
    '405': 'Enroute-Holding (IFR)',
    '450': 'Maneuvering',
    '451': 'Maneuvering-Aerobatics',
    '452': 'Maneuvering-Low-alt flying',
    '453': 'Maneuvering-Hover',
    '500': 'Approach',
    '501': 'Approach-IFR Initial Approach',
    '502': 'Approach-IFR Final Approach',
    '503': 'Approach-Circling (IFR)',
    '505': 'Approach-VFR Pattern Crosswind',
    '506': 'Approach-VFR Pattern Downwind',
    '507': 'Approach-VFR Pattern Base',
    '508': 'Approach-VFR Pattern Final',
    '509': 'Approach-VFR Go-Around',
    '550': 'Landing',
    '551': 'Landing-Flare/Touchdown',
    '552': 'Landing-Landing Roll',
    '600': 'Emergency Descent',
    '650': 'Uncontrolled Descent',
    '700': 'Post-Impact',
    '750': 'After Landing',
    '800': 'Other',
    '990': 'Unknown'

}


`phase_no` became int64 at some poin in my EDA so now I need to convert it back to string (I discovered something went wrong when previewing the new column and seeing all the values were `'Unknown specific phase of flight'`)

In [ ]:
# confirming data type
print(type(df_events_sequence_str_copy['phase_no'].iloc[0]))


<class 'numpy.int64'>


In [ ]:
# making phase_no a string type

df_events_sequence_str_copy['phase_no'] = df_events_sequence_str_copy['phase_no'].astype(str)


In [ ]:
# Creating a new 'specific phase of flight' column by mapping 'phase_no' with the dictionary

df_events_sequence_str_copy['specific phase of flight'] = df_events_sequence_str_copy['phase_no'].map(specific_phase_dict).fillna('Unknown specific phase')

In [ ]:
# Let's preview the work!
df_events_sequence_str_copy.head(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
0  20080107X00026             1              1           550250   
1  20080107X00026             2              1           350250   
2  20080109X00036             1              1           551230   

                              Occurrence_Description phase_no eventsoe_no  \
0                           Landing Midair collision      550         250   
1                     Initial climb Midair collision      350         250   
2  Landing-flare/touchdown Loss of control on ground      551         230   

   Defining_ev          lchg_date  lchg_userid broad phase of flight  \
0            1  09/25/20 18:05:31          NaN               Landing   
1            1  09/25/20 18:05:31          NaN         Initial Climb   
2            1  09/25/20 18:05:31          NaN               Landing   

   broad_phase_no                 Occurrence specific phase of flight  
0              55           Midair collision                  Landing  
1              35           Midair collision            Initial Climb  
2              55  Loss of control on ground  Landing-Flare/Touchdown

In [ ]:
df_events_sequence_str_copy.tail(3)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
55620  20230427107158             1              1           550094   
55621  20230427107159             1              1           400342   
55622  20230430107167             1              1           990200   

                       Occurrence_Description phase_no eventsoe_no  \
55620           Landing Landing gear collapse      550         094   
55621  Enroute Loss of engine power (partial)      400         342   
55622                Unknown Ground collision      990         200   

       Defining_ev          lchg_date  lchg_userid broad phase of flight  \
55620            1  04/27/23 16:05:58          NaN               Landing   
55621            1  04/27/23 16:11:51          NaN               Enroute   
55622            1  04/30/23 12:51:33          NaN               Unknown   

       broad_phase_no                      Occurrence specific phase of flight  
55620              55           Landing gear collapse                  Landing  
55621              40  Loss of engine power (partial)                  Enroute  
55622              99                Ground collision                  Unknown

In [ ]:
#exporting csv to my google drive
#from google.colab import drive
#drive.mount('/content/drive')
path = '/content/drive/My Drive/df_events_sequence_str_copy.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_events_sequence_str_copy.to_csv(f)

##Reading in and selecting columns from `findings.csv`.
(Note: we wound up not using this table in our final dataset.)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving findings.csv to findings.csv


In [ ]:
df_findings = pd.read_csv('findings.csv')

In [ ]:
df_findings.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  finding_no  finding_code  \
0      20080107X00026             1           1     204151045   
1      20080107X00026             2           1     204151044   
2      20080109X00036             1           1     303404099   
3      20080109X00036             1           2     106202020   
4      20080107X00027             1           1     303602099   
...               ...           ...         ...           ...   
60683  20230320106920             1           1     206304044   
60684  20230320106920             1           4     303404083   
60685  20230320106920             1           3     302301581   
60686  20230324106947             1           1     206304044   
60687  20230324106947             1           2     302302081   

                                     finding_description  category_no  \
0      Personnel issues-Action/decision-Info processi...            2   
1      Personnel issues-Action/decision-I

In [ ]:
df_findings.columns

Index(['ev_id', 'Aircraft_Key', 'finding_no', 'finding_code',
       'finding_description', 'category_no', 'subcategory_no', 'section_no',
       'subsection_no', 'modifier_no', 'Cause_Factor', 'lchg_date',
       'lchg_userid'],
      dtype='object')

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key','finding_no', 'finding_code',
       'finding_description', 'category_no','modifier_no', 'Cause_Factor']

df_findings_edit = df_findings[selected_columns].copy()

In [ ]:
df_findings_edit.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  finding_no  finding_code  \
0      20080107X00026             1           1     204151045   
1      20080107X00026             2           1     204151044   
2      20080109X00036             1           1     303404099   
3      20080109X00036             1           2     106202020   
4      20080107X00027             1           1     303602099   
...               ...           ...         ...           ...   
60683  20230320106920             1           1     206304044   
60684  20230320106920             1           4     303404083   
60685  20230320106920             1           3     302301581   
60686  20230324106947             1           1     206304044   
60687  20230324106947             1           2     302302081   

                                     finding_description  category_no  \
0      Personnel issues-Action/decision-Info processi...            2   
1      Personnel issues-Action/decision-I

In [ ]:
df_findings_edit.columns

Index(['ev_id', 'Aircraft_Key', 'finding_no', 'finding_code',
       'finding_description', 'category_no', 'modifier_no', 'Cause_Factor'],
      dtype='object')

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_findings_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_findings_edit.to_csv(f)

##Reading in and selecting columns from `flight_crew.csv`.
(Note: we wound up not using this table in our final dataset.)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving flight_crew.csv to flight_crew.csv


In [ ]:
df_flight_crew = pd.read_csv('flight_crew.csv')

In [ ]:
df_flight_crew.info 

<bound method DataFrame.info of                 ev_id  Aircraft_Key  crew_no crew_category  crew_age crew_sex  \
0      20080107X00026             1        1           PLT      56.0        M   
1      20080107X00026             2        1           PLT      70.0        M   
2      20080109X00036             1        1           PLT      54.0        F   
3      20080107X00027             1        1           PLT      59.0        M   
4      20080115X00051             1        1          DSTU      36.0        M   
...               ...           ...      ...           ...       ...      ...   
26182  20230313106884             1        1           PLT      51.0        M   
26183  20230313106885             1        1           PLT      63.0        M   
26184  20230313106889             1        2          DSTU      19.0        M   
26185  20230320106920             1        1           PLT      54.0        M   
26186  20230324106947             1        1           PLT      60.0        M

In [ ]:
df_flight_crew.columns

Index(['ev_id', 'Aircraft_Key', 'crew_no', 'crew_category', 'crew_age',
       'crew_sex', 'crew_city', 'crew_res_state', 'crew_res_country',
       'med_certf', 'med_crtf_vldty', 'date_lst_med', 'crew_rat_endorse',
       'crew_inj_level', 'seatbelts_used', 'shldr_harn_used', 'crew_tox_perf',
       'seat_occ_pic', 'pc_profession', 'bfr', 'bfr_date', 'ft_as_of',
       'lchg_date', 'lchg_userid', 'seat_occ_row', 'infl_rest_inst',
       'infl_rest_depl', 'child_restraint', 'med_crtf_limit',
       'mr_faa_med_certf', 'pilot_flying', 'available_restraint',
       'restraint_used'],
      dtype='object')

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key','mr_faa_med_certf', 'med_crtf_vldty','pc_profession','bfr', 'bfr_date', 'crew_age', 'crew_category', 
                    'crew_inj_level','crew_rat_endorse', 'crew_tox_perf']

df_flight_crew_edit = df_flight_crew[selected_columns].copy()

In [ ]:
df_flight_crew_edit.info 

<bound method DataFrame.info of                 ev_id  Aircraft_Key mr_faa_med_certf med_crtf_vldty  \
0      20080107X00026             1              NaN            WWL   
1      20080107X00026             2              NaN            WWL   
2      20080109X00036             1              NaN            WWL   
3      20080107X00027             1              NaN            NaN   
4      20080115X00051             1              NaN           WOWL   
...               ...           ...              ...            ...   
26182  20230313106884             1              NaN            WWL   
26183  20230313106885             1              NaN            WWL   
26184  20230313106889             1              NaN            WWL   
26185  20230320106920             1              NaN            WWL   
26186  20230324106947             1              NaN            WWL   

      pc_profession  bfr           bfr_date  crew_age crew_category  \
0                No  NaN  07/01/07 00:00:00 

In [ ]:
df_flight_crew_edit.columns 

Index(['ev_id', 'Aircraft_Key', 'mr_faa_med_certf', 'med_crtf_vldty',
       'pc_profession', 'bfr', 'bfr_date', 'crew_age', 'crew_category',
       'crew_inj_level', 'crew_rat_endorse', 'crew_tox_perf'],
      dtype='object')

In [ ]:
# exporting csv to google drive
path = '/content/drive/My Drive/df_flight_crew_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_flight_crew_edit.to_csv(f)

##Reading in and selecting columns from `injury.csv`.
(Note: we wound up not using this table in our final dataset.)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving injury.csv to injury.csv


In [ ]:
df_injury = pd.read_csv('injury.csv')

In [ ]:
df_injury.info 

<bound method DataFrame.info of                 ev_id  Aircraft_Key inj_person_category injury_level  \
0      20080211X00175             1                Crew         NONE   
1      20080211X00175             1                Crew         TOTL   
2      20080107X00026             1                Crew         NONE   
3      20080107X00026             1                Crew         TOTL   
4      20080107X00026             2                Crew         NONE   
...               ...           ...                 ...          ...   
76711  20230427107159             1                Crew         TOTL   
76712  20230430107167             1                Crew         FATL   
76713  20230430107167             1                Crew         TOTL   
76714  20230430107167             1                Pass         FATL   
76715  20230430107167             1                Pass         TOTL   

       inj_person_count          lchg_date lchg_userid  
0                   2.0  09/25/20 18:07:50    

In [ ]:
df_injury.columns

Index(['ev_id', 'Aircraft_Key', 'inj_person_category', 'injury_level',
       'inj_person_count', 'lchg_date', 'lchg_userid'],
      dtype='object')

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key', 'inj_person_category', 'injury_level',
       'inj_person_count']
df_injury_edit = df_injury[selected_columns].copy()

In [ ]:
path = '/content/drive/My Drive/df_injury_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_injury_edit.to_csv(f)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving flight_time.csv to flight_time.csv


In [ ]:
df_flight_time = pd.read_csv('flight_time.csv')

In [ ]:
df_flight_time.info

<bound method DataFrame.info of                  ev_id  Aircraft_Key  crew_no flight_type flight_craft  \
0       20080107X00026             1        1        L90D         ACTU   
1       20080107X00026             1        1        L90D          ALL   
2       20080107X00026             1        1        L90D         MAKE   
3       20080107X00026             1        1        L90D         SENG   
4       20080107X00026             1        1        L90D         SIMU   
...                ...           ...      ...         ...          ...   
326294  20230324106947             1        1        TOTL         MENG   
326295  20230324106947             1        1        TOTL         NGHT   
326296  20230324106947             1        1        TOTL         ROTO   
326297  20230324106947             1        1        TOTL         SENG   
326298  20230324106947             1        1        TOTL         SIMU   

        flight_hours          lchg_date lchg_userid  
0                3.0  09/

In [ ]:
df_flight_time.columns

Index(['ev_id', 'Aircraft_Key', 'crew_no', 'flight_type', 'flight_craft',
       'flight_hours', 'lchg_date', 'lchg_userid'],
      dtype='object')

In [ ]:
selected_columns = ['ev_id', 'Aircraft_Key','flight_type', 'flight_craft']
df_flight_time_edit = df_flight_time[selected_columns].copy()

In [ ]:
path = '/content/drive/My Drive/df_flight_time_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df_flight_time_edit.to_csv(f)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving narratives.csv to narratives.csv


In [ ]:
df_narratives = pd.read_csv('narratives.csv')

In [ ]:
df_narratives.info

<bound method DataFrame.info of                 ev_id  Aircraft_Key  \
0      20080211X00175             1   
1      20080107X00026             1   
2      20080107X00026             2   
3      20080109X00036             1   
4      20080107X00027             1   
...               ...           ...   
24504  20230415107060             1   
24505  20230420107091             1   
24506  20230420107092             1   
24507  20230420107095             1   
24508  20230424107106             1   

                                               narr_accp  \
0      On January 10, 2008, an American registered Eu...   
1      On January 1, 2008, about 1430 Pacific standar...   
2      On January 1, 2008, about 1430 Pacific standar...   
3      The private pilot was conducting a touch-and-g...   
4      On January 3, 2008, approximately 0225 central...   
...                                                  ...   
24504  On April 15, 2023, about 1039 eastern daylight...   
24505  On April 19,

In [ ]:
df_narratives.columns

Index(['ev_id', 'Aircraft_Key', 'narr_accp', 'narr_accf', 'narr_cause',
       'narr_inc', 'lchg_date', 'lchg_userid'],
      dtype='object')

In [ ]:
selected_columns =['ev_id', 'Aircraft_Key','narr_accp', 'narr_accf', 'narr_cause','narr_inc']

df_narratives_edit = df_narratives[selected_columns].copy()

In [ ]:
path = '/content/drive/My Drive/df_narratives_edit.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
 df_narratives_edit.to_csv(f)

#At last: recreating the Aviation DataFrame with clean data!

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving df_events_sequence_str_copy-with-phase-columns.csv to df_events_sequence_str_copy-with-phase-columns.csv


In [ ]:
df_events_sequence.head(1)

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
0  20080107X00026             1              1           550250   

     Occurrence_Description  phase_no  eventsoe_no  Defining_ev  \
0  Landing Midair collision       550          250            1   

           lchg_date  lchg_userid  
0  09/25/20 18:05:31          NaN

In [ ]:
df_events_sequence_og = pd.read_csv('df_events_sequence_str_copy-with-phase-columns.csv')

In [ ]:
# double checking I have all the dataframes and columns I need 
selected_columns =['ev_id', 'Aircraft_Key','broad phase of flight', 'specific phase of flight', 'Occurrence', 'phase_no', 'broad_phase_no', 'eventsoe_no']

df_events_sequence_og_edit = df_events_sequence_og[selected_columns].copy()

In [ ]:
# looking good!
df_events_sequence_og_edit.head(3)

ev_id  Aircraft_Key broad phase of flight  \
0  20080107X00026             1               Landing   
1  20080107X00026             2         Initial Climb   
2  20080109X00036             1               Landing   

  specific phase of flight                 Occurrence  phase_no  \
0                  Landing           Midair collision       550   
1            Initial Climb           Midair collision       350   
2  Landing-Flare/Touchdown  Loss of control on ground       551   

   broad_phase_no  eventsoe_no  
0              55          250  
1              35          250  
2              55          230

In [ ]:
df_aifcraft_og_replace2.head(3)

ev_id  Aircraft_Key      ntsb_no regis_no acft_category  \
0  20080211X00175             1   DFW08RA039   N530NA          HELI   
1  20080107X00026             1  SEA08LA057A   N8037W           AIR   
2  20080107X00026             2  SEA08LA057B    N15EX           AIR   

           acft_make acft_model homebuilt far_part  num_eng type_fly damage  
0  Eurocopter France    AS350B3         N     NUSN      NaN     EXLD   SUBS  
1              PIPER  PA 28-180         N      091      1.0     PERS   MINR  
2    Barnard/Stancil    Glastar         Y      091      1.0     PERS   SUBS

In [ ]:
df_aircraft.head(3)

ev_id  Aircraft_Key regis_no      ntsb_no acft_missing far_part  \
0  20080211X00175             1   N530NA   DFW08RA039            N     NUSN   
1  20080107X00026             1   N8037W  SEA08LA057A            N      091   
2  20080107X00026             2    N15EX  SEA08LA057B            N      091   

  flt_plan_filed flight_plan_activated damage acft_fire  ... acft_year  \
0            NaN                   NaN   SUBS       NaN  ...       NaN   
1           NONE                   NaN   MINR      NONE  ...       NaN   
2           NONE                   NaN   SUBS      NONE  ...       NaN   

  fuel_on_board commercial_space_flight unmanned ifr_equipped_cert  \
0           NaN                       0        0                 0   
1           NaN                       0        0                 0   
2           NaN                       0        0                 0   

   elt_mounted_aircraft elt_connected_antenna  elt_manufacturer elt_model  \
0                     0                     0               NaN       NaN   
1                     0                     0               NaN       NaN   
2                     0                     0               NaN       NaN   

   elt_reason_other  
0               NaN  
1               NaN  
2               NaN  

[3 rows x 93 columns]

In [ ]:
#let me just grab these columns in the order I want them...
selected_columns = ['ev_id', 'ntsb_no', 'Aircraft_Key', 'acft_category', 'type_fly', 'acft_make', 'acft_model', 'homebuilt', 'num_eng', 'damage', 'far_part', 'regis_no']
df_airfcraft_og_edit = df_aircraft[selected_columns].copy()

In [ ]:
df_engines.head(1)

ev_id  Aircraft_Key  eng_no eng_type          eng_mfgr  eng_model  \
0  20080107X00026             1       1      REC  Textron Lycoming  O-360-A3A   

   power_units hp_or_lbs lchg_userid          lchg_date carb_fuel_injection  \
0        180.0        HP         NaN  09/25/20 18:05:31                CARB   

  propeller_type propeller_make propeller_model  eng_time_total  \
0            NaN            NaN             NaN               0   

   eng_time_last_insp  eng_time_overhaul  
0                   0                  0

In [ ]:
#grabbing the columns from engines.csv that I need to do the rebuild 
selected_columns = ['ev_id', 'Aircraft_Key', 'eng_no', 'eng_type']
df_engines_og_edit = df_engines[selected_columns].copy()

In [ ]:
df_engines_og_edit.head(3)

ev_id  Aircraft_Key  eng_no eng_type
0  20080107X00026             1       1      REC
1  20080107X00026             2       1      REC
2  20080109X00036             1       1      REC

In [ ]:
#grabbing the columns I need from the events dataframe
selected_columns = ['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'ev_city', 'ev_state', 'ev_country', 'latitude', 'longitude', 'ev_nr_apt_id', 'apt_name', 'ev_highest_injury',
       'inj_tot_f','inj_tot_s', 'inj_tot_m','inj_tot_n' , 'wx_cond_basic', ]
df_events_og_edit = df_events[selected_columns].copy()

In [ ]:
# now I am going to merge df_airfcraft_og_edit, df_events_sequence_og_edit, and df_engines_og_edit, 
# these three have the 'Aircraft_Key' whereas events.csv does not

# first merge df_airfcraft_og_edit + df_events_sequence_og_edit
df_aircraft_combined = df_airfcraft_og_edit.merge(df_events_sequence_og_edit, on=['ev_id', 'Aircraft_Key'], how='left')

# second merge df_aircraft_combined with df_engines_og_edit
df_aircraft_combined = df_aircraft_combined.merge(df_engines_og_edit, on=['ev_id',	'Aircraft_Key'],  how='left') 

# finally merge df_aircraft_combind with df_events_og_edit to put it all together and make the final rebuild!!!
df = df_events_og_edit.merge(df_aircraft_combined, on=['ev_id', 'ntsb_no'], how='left') 

##Getting to know our new dataframe

In [ ]:
df.columns

Index(['ev_id', 'ntsb_no', 'ev_type', 'ev_date', 'ev_city', 'ev_state',
       'ev_country', 'latitude', 'longitude', 'ev_nr_apt_id', 'apt_name',
       'ev_highest_injury', 'inj_tot_f', 'inj_tot_s', 'inj_tot_m', 'inj_tot_n',
       'wx_cond_basic', 'Aircraft_Key', 'acft_category', 'type_fly',
       'acft_make', 'acft_model', 'homebuilt', 'num_eng', 'damage', 'far_part',
       'regis_no', 'broad phase of flight', 'specific phase of flight',
       'Occurrence', 'phase_no', 'broad_phase_no', 'eventsoe_no', 'eng_no',
       'eng_type'],
      dtype='object')

In [ ]:
df.head()


ev_id     ntsb_no ev_type            ev_date          ev_city  \
0  20080211X00175  DFW08RA039     ACC  01/10/08 00:00:00  Pitt Meadow, BC   
1  20080107X00026  SEA08LA057     ACC  01/01/08 00:00:00           Sonoma   
2  20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00           Arcola   
3  20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00           Arcola   
4  20080107X00027  DFW08LA055     ACC  01/03/08 00:00:00    Oklahoma City   

  ev_state ev_country latitude longitude ev_nr_apt_id  ... far_part regis_no  \
0      NaN         CA      NaN       NaN          NaN  ...     NUSN   N530NA   
1       CA        USA  381326N  1222659W          OQ3  ...      NaN      NaN   
2       TX        USA  293022N  0952836W          AXH  ...      091   N579RM   
3       TX        USA  293022N  0952836W          AXH  ...      091   N579RM   
4       OK        USA  035321N  0973829W          PWA  ...      091    N398J   

   broad phase of flight      specific phase of flight  \
0                    NaN                           NaN   
1                    NaN                           NaN   
2                Landing       Landing-Flare/Touchdown   
3                Landing                       Landing   
4               Standing  Standing-Engine(s) Operating   

                       Occurrence  phase_no broad_phase_no  eventsoe_no  \
0                             NaN       NaN            NaN          NaN   
1                             NaN       NaN            NaN          NaN   
2       Loss of control on ground     551.0           55.0        230.0   
3                Runway excursion     550.0           55.0        300.0   
4  AC/prop/rotor contact w person     153.0           15.0         81.0   

  eng_no eng_type  
0    NaN      NaN  
1    NaN      NaN  
2    1.0      REC  
3    1.0      REC  
4    1.0       TP  

[5 rows x 35 columns]

In [ ]:
# changing the column order again

selected_columns = ['ev_id', 'ntsb_no', 'ev_type', 'Aircraft_Key', 'acft_category', 'type_fly', 'acft_make', 'acft_model',  'homebuilt', 'num_eng', 'eng_no', 'eng_type','damage', 'far_part','regis_no','ev_date', 'ev_city', 'ev_state',
       'ev_country', 'latitude', 'longitude', 'ev_nr_apt_id', 'apt_name',
       'ev_highest_injury', 'inj_tot_f', 'inj_tot_s', 'inj_tot_m', 'inj_tot_n',
       'wx_cond_basic', 'broad phase of flight', 'specific phase of flight', 'Occurrence',
       'phase_no', 'broad_phase_no', 'eventsoe_no']
df = df[selected_columns].copy()

In [ ]:
df.head()

ev_id     ntsb_no ev_type  Aircraft_Key acft_category type_fly  \
0  20080211X00175  DFW08RA039     ACC           1.0          HELI     EXLD   
1  20080107X00026  SEA08LA057     ACC           NaN           NaN      NaN   
2  20080109X00036  DFW08CA054     ACC           1.0           AIR     PERS   
3  20080109X00036  DFW08CA054     ACC           1.0           AIR     PERS   
4  20080107X00027  DFW08LA055     ACC           1.0           AIR     PERS   

                acft_make acft_model homebuilt  num_eng  ...  inj_tot_s  \
0       Eurocopter France    AS350B3         N      NaN  ...          0   
1                     NaN        NaN       NaN      NaN  ...          0   
2  Micco Aircraft Company   MAC-145B         N      1.0  ...          0   
3  Micco Aircraft Company   MAC-145B         N      1.0  ...          0   
4                 Pilatus   PC-12/45         N      1.0  ...          0   

  inj_tot_m inj_tot_n wx_cond_basic broad phase of flight  \
0         0         2           NaN                   NaN   
1         0         3           VMC                   NaN   
2         0         1           VMC               Landing   
3         0         1           VMC               Landing   
4         0         8           VMC              Standing   

       specific phase of flight                      Occurrence phase_no  \
0                           NaN                             NaN      NaN   
1                           NaN                             NaN      NaN   
2       Landing-Flare/Touchdown       Loss of control on ground    551.0   
3                       Landing                Runway excursion    550.0   
4  Standing-Engine(s) Operating  AC/prop/rotor contact w person    153.0   

  broad_phase_no eventsoe_no  
0            NaN         NaN  
1            NaN         NaN  
2           55.0       230.0  
3           55.0       300.0  
4           15.0        81.0  

[5 rows x 35 columns]

In [ ]:
df.tail()

ev_id     ntsb_no ev_type  Aircraft_Key acft_category  \
60394  20230426107154  WPR23LA168     ACC           1.0           NaN   
60395  20230427107155  ERA23LA210     ACC           1.0           NaN   
60396  20230427107158  GAA23WA136     ACC           1.0           NaN   
60397  20230427107159  GAA23WA137     ACC           1.0           NaN   
60398  20230430107167  WPR23FA172     ACC           1.0           NaN   

      type_fly  acft_make acft_model homebuilt  num_eng  ...  inj_tot_s  \
60394     PERS     CESSNA        140         N      NaN  ...          0   
60395     PERS      PIPER      PA-30         N      NaN  ...          0   
60396      NaN  Jetstream       3112         N      NaN  ...          0   
60397      NaN     CESSNA        172         N      NaN  ...          0   
60398      NaN     CESSNA       172S         N      NaN  ...          0   

      inj_tot_m inj_tot_n wx_cond_basic broad phase of flight  \
60394         1         0           NaN                   NaN   
60395         0         4           NaN                   NaN   
60396         0         2           NaN                   NaN   
60397         0         2           NaN                   NaN   
60398         0         0           NaN                   NaN   

      specific phase of flight Occurrence phase_no broad_phase_no eventsoe_no  
60394                      NaN        NaN      NaN            NaN         NaN  
60395                      NaN        NaN      NaN            NaN         NaN  
60396                      NaN        NaN      NaN            NaN         NaN  
60397                      NaN        NaN      NaN            NaN         NaN  
60398                      NaN        NaN      NaN            NaN         NaN  

[5 rows x 35 columns]

In [ ]:
df.info

<bound method DataFrame.info of                 ev_id     ntsb_no ev_type  Aircraft_Key acft_category  \
0      20080211X00175  DFW08RA039     ACC           1.0          HELI   
1      20080107X00026  SEA08LA057     ACC           NaN           NaN   
2      20080109X00036  DFW08CA054     ACC           1.0           AIR   
3      20080109X00036  DFW08CA054     ACC           1.0           AIR   
4      20080107X00027  DFW08LA055     ACC           1.0           AIR   
...               ...         ...     ...           ...           ...   
60394  20230426107154  WPR23LA168     ACC           1.0           NaN   
60395  20230427107155  ERA23LA210     ACC           1.0           NaN   
60396  20230427107158  GAA23WA136     ACC           1.0           NaN   
60397  20230427107159  GAA23WA137     ACC           1.0           NaN   
60398  20230430107167  WPR23FA172     ACC           1.0           NaN   

      type_fly               acft_make acft_model homebuilt  num_eng  ...  \
0         EXLD

In [ ]:
len(df)

60399

In [ ]:
df.columns

Index(['ev_id', 'ntsb_no', 'ev_type', 'Aircraft_Key', 'acft_category',
       'type_fly', 'acft_make', 'acft_model', 'homebuilt', 'num_eng', 'eng_no',
       'eng_type', 'damage', 'far_part', 'regis_no', 'ev_date', 'ev_city',
       'ev_state', 'ev_country', 'latitude', 'longitude', 'ev_nr_apt_id',
       'apt_name', 'ev_highest_injury', 'inj_tot_f', 'inj_tot_s', 'inj_tot_m',
       'inj_tot_n', 'wx_cond_basic', 'broad phase of flight',
       'specific phase of flight', 'Occurrence', 'phase_no', 'broad_phase_no',
       'eventsoe_no'],
      dtype='object')

In [ ]:
df['ev_state'].unique

<bound method Series.unique of 0        NaN
1         CA
2         TX
3         TX
4         OK
        ... 
60394     OR
60395     FL
60396    NaN
60397    NaN
60398     CA
Name: ev_state, Length: 60399, dtype: object>

In [ ]:
df.info

<bound method DataFrame.info of                 ev_id     ntsb_no ev_type  Aircraft_Key acft_category  \
0      20080211X00175  DFW08RA039     ACC           1.0          HELI   
1      20080107X00026  SEA08LA057     ACC           NaN           NaN   
2      20080109X00036  DFW08CA054     ACC           1.0           AIR   
3      20080109X00036  DFW08CA054     ACC           1.0           AIR   
4      20080107X00027  DFW08LA055     ACC           1.0           AIR   
...               ...         ...     ...           ...           ...   
60394  20230426107154  WPR23LA168     ACC           1.0           NaN   
60395  20230427107155  ERA23LA210     ACC           1.0           NaN   
60396  20230427107158  GAA23WA136     ACC           1.0           NaN   
60397  20230427107159  GAA23WA137     ACC           1.0           NaN   
60398  20230430107167  WPR23FA172     ACC           1.0           NaN   

      type_fly               acft_make acft_model homebuilt  num_eng  ...  \
0         EXLD

Recall that `events.csv` is organized around the event (accident or incident). Each record or row is distinct and contains all the information about one event. It does not contain `'Aircraft_Key'` as it does not deal with specific aircraft whether an event is multi aircraft or not. `aircraft.csv` , `engines.csv` and `events_sequence.csv` all deal with specific aircraft and contain multiple records about the same event.

This means merging these datasets together will create NaN valus in some columns. 

In [ ]:
nan_count_whole_df = df.isna().sum() 
nan_count_whole_df

ev_id                           0
ntsb_no                         0
ev_type                         0
Aircraft_Key                  774
acft_category                1122
type_fly                     7922
acft_make                     818
acft_model                    829
homebuilt                     774
num_eng                      5251
eng_no                       6529
eng_type                     6844
damage                       2906
far_part                     1540
regis_no                      811
ev_date                         0
ev_city                        22
ev_state                     4876
ev_country                      0
latitude                     2934
longitude                    2933
ev_nr_apt_id                19746
apt_name                    19282
ev_highest_injury            1245
inj_tot_f                       0
inj_tot_s                       0
inj_tot_m                       0
inj_tot_n                       0
wx_cond_basic                4395
broad phase of

In [ ]:
# exporting  csv to google drive
#from google.colab import drive
#drive.mount('/content/drive')
path = '/content/drive/My Drive/df.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df.to_csv(f)

In [ ]:
# creating a copy to edit 
df_copy = df.copy()

See duplicate rows based on `ntsb_no ` (known as the `Accident.Number` column in the Kaggle dataset).

In [ ]:
duplicate = df_copy[df_copy.duplicated('ntsb_no')]

print("Duplicate Rows based on docket number :")

duplicate

Duplicate Rows based on docket number :


ev_id     ntsb_no ev_type  Aircraft_Key acft_category  \
3      20080109X00036  DFW08CA054     ACC           1.0           AIR   
6      20080115X00051  DEN08CA047     ACC           1.0           AIR   
8      20080115X00047  MIA08LA035     ACC           1.0           AIR   
10     20080123X00096  NYC08LA075     ACC           1.0           AIR   
12     20080116X00063  ANC08MA038     ACC           1.0           AIR   
...               ...         ...     ...           ...           ...   
59069  20220627105360  ERA22LA286     ACC           1.0           AIR   
59074  20220627105367  ERA22LA287     ACC           1.0           AIR   
59075  20220627105367  ERA22LA287     ACC           1.0           AIR   
59077  20220627105368  WPR22LA232     ACC           1.0           AIR   
59079  20220627105370  WPR22LA233     ACC           1.0           AIR   

      type_fly               acft_make acft_model homebuilt  num_eng  ...  \
3         PERS  Micco Aircraft Company   MAC-145B         N      1.0  ...   
6         INST                  Cessna        152         N      1.0  ...   
8         PERS                  Cessna      R172K         N      1.0  ...   
10        PERS          DEAN PATRICK G    GENESIS         Y      1.0  ...   
12         NaN                   PIPER  PA-31-350         N      2.0  ...   
...        ...                     ...        ...       ...      ...  ...   
59069     PERS                   PIPER  PA-38-112         N      1.0  ...   
59074     PERS         MANTELL ALLAN T  LIGHTNING         Y      1.0  ...   
59075     PERS         MANTELL ALLAN T  LIGHTNING         Y      1.0  ...   
59077     PERS                   MAULE   MX-7-235         N      1.0  ...   
59079     PERS        GMK VENTURES LLC       AL18         N      1.0  ...   

       inj_tot_s inj_tot_m inj_tot_n wx_cond_basic broad phase of flight  \
3              0         0         1           VMC               Landing   
6              0         0         1           VMC               Landing   
8              0         1         0           VMC               Landing   
10             0         1         0           VMC  Uncontrolled Descent   
12             3         1         0           VMC         Initial Climb   
...          ...       ...       ...           ...                   ...   
59069          0         0         2           VMC               Landing   
59074          1         0         0           VMC               Landing   
59075          1         0         0           VMC               Landing   
59077          0         0         1           VMC   Unknown broad phase   
59079          0         0         1           VMC               Landing   

      specific phase of flight                          Occurrence phase_no  \
3                      Landing                    Runway excursion    550.0   
6      Landing-Flare/Touchdown  Collision with terr/obj (non-CFIT)    551.0   
8         Landing-Landing Roll  Collision with terr/obj (non-CFIT)    552.0   
10        Uncontrolled Descent  Collision with terr/obj (non-CFIT)    650.0   
12               Initial Climb      Sys/Comp malf/fail (non-power)    350.0   
...                        ...                                 ...      ...   
59069  Landing-Flare/Touchdown                    Runway excursion    551.0   
59074     Landing-Landing Roll      Off-field or emergency landing    552.0   
59075     Landing-Landing Roll               Landing gear collapse    552.0   
59077                  Takeoff           Loss of control on ground    300.0   
59079  Landing-Flare/Touchdown       Collision during takeoff/land    551.0   

      broad_phase_no eventsoe_no  
3               55.0       300.0  
6               55.0       470.0  
8               55.0       470.0  
10              65.0       470.0  
12              35.0       330.0  
...              ...         ...  
59069           55.0       300.0  
59074           55.0       440.0  
59075           55.0        94.0  
59

In [ ]:
df.duplicated().sum()

7

In [ ]:
duplicate.head()

ev_id     ntsb_no ev_type  Aircraft_Key acft_category type_fly  \
3   20080109X00036  DFW08CA054     ACC           1.0           AIR     PERS   
6   20080115X00051  DEN08CA047     ACC           1.0           AIR     INST   
8   20080115X00047  MIA08LA035     ACC           1.0           AIR     PERS   
10  20080123X00096  NYC08LA075     ACC           1.0           AIR     PERS   
12  20080116X00063  ANC08MA038     ACC           1.0           AIR      NaN   

                 acft_make acft_model homebuilt  num_eng  ...  inj_tot_s  \
3   Micco Aircraft Company   MAC-145B         N      1.0  ...          0   
6                   Cessna        152         N      1.0  ...          0   
8                   Cessna      R172K         N      1.0  ...          0   
10          DEAN PATRICK G    GENESIS         Y      1.0  ...          0   
12                   PIPER  PA-31-350         N      2.0  ...          3   

   inj_tot_m inj_tot_n wx_cond_basic broad phase of flight  \
3          0         1           VMC               Landing   
6          0         1           VMC               Landing   
8          1         0           VMC               Landing   
10         1         0           VMC  Uncontrolled Descent   
12         1         0           VMC         Initial Climb   

   specific phase of flight                          Occurrence phase_no  \
3                   Landing                    Runway excursion    550.0   
6   Landing-Flare/Touchdown  Collision with terr/obj (non-CFIT)    551.0   
8      Landing-Landing Roll  Collision with terr/obj (non-CFIT)    552.0   
10     Uncontrolled Descent  Collision with terr/obj (non-CFIT)    650.0   
12            Initial Climb      Sys/Comp malf/fail (non-power)    350.0   

   broad_phase_no eventsoe_no  
3            55.0       300.0  
6            55.0       470.0  
8            55.0       470.0  
10           65.0       470.0  
12           35.0       330.0  

[5 rows x 35 columns]

Let's compare a random record from `aircraft.csv` to that same event in `events.csv` and `event_sequence.csv` so we can visualize the difference on structure between the three.

In [ ]:
df_aircraft_NYC08CA301 = df_aircraft[df_aircraft['ntsb_no'] == 'NYC08CA301']


In [ ]:
df_aircraft_NYC08CA301

ev_id  Aircraft_Key regis_no     ntsb_no acft_missing far_part  \
1341  20081003X17831             1    N69RV  NYC08CA301            N      091   

     flt_plan_filed flight_plan_activated damage acft_fire  ... acft_year  \
1341           NONE                     N   SUBS      NONE  ...       NaN   

     fuel_on_board commercial_space_flight unmanned ifr_equipped_cert  \
1341           NaN                       0        0                 0   

      elt_mounted_aircraft elt_connected_antenna  elt_manufacturer elt_model  \
1341                     0                     0               NaN       NaN   

      elt_reason_other  
1341               NaN  

[1 rows x 93 columns]

In [ ]:
df_events_NYC08CA301 = df_events[df_events['ntsb_no'] == 'NYC08CA301']

In [ ]:
df_events_NYC08CA301


ev_id     ntsb_no ev_type            ev_date ev_dow  ev_time  \
1315  20081003X17831  NYC08CA301     ACC  09/02/08 00:00:00     Tu   1920.0   

     ev_tmzn       ev_city ev_state ev_country  ...  ntsb_notf_from  \
1315     UTC  Toughkenamon       PA        USA  ...             NaN   

      ntsb_notf_date  ntsb_notf_tm fiche_number          lchg_date  \
1315             NaN           NaN          NaN  09/25/20 18:05:31   

     lchg_userid wx_cond_basic faa_dist_office dec_latitude dec_longitude  
1315         NaN           VMC             NaN    39.830276    -75.769721  

[1 rows x 73 columns]

There is no `ntsb_no` in `events_sequence.csv` however it does have `ev_id` and the `ev_id` associated with the `ntsb_no `of the event we are looking at (`'NYC08CA301'`)  is 2`0081003X17831`.

In [ ]:
df_events_sequence_20081003X17831 = df_events_sequence[df_events_sequence['ev_id'] == '20081003X17831']

**What looks like 3 duplicate records is actually showing the sequence of events. Note the `Occurrence_No` column.**

In [ ]:
df_events_sequence_20081003X17831 

ev_id  Aircraft_Key  Occurrence_No  Occurrence_Code  \
2692  20081003X17831             1              1           551090   
2693  20081003X17831             1              2           552094   
2694  20081003X17831             1              3           552300   

                               Occurrence_Description  phase_no  eventsoe_no  \
2692  Landing-flare/touchdown Abnormal runway contact       551           90   
2693       Landing-landing roll Landing gear collapse       552           94   
2694            Landing-landing roll Runway excursion       552          300   

      Defining_ev          lchg_date  lchg_userid  
2692            0  09/25/20 18:05:31          NaN  
2693            1  09/25/20 18:05:31          NaN  
2694            0  09/25/20 18:05:31          NaN

Remake the dataframe with the `Occurrence_No `column so we don't lose that information and mistake these rows for duplicate records.

In [ ]:
# adding the Occurrence_No columns
selected_columns =['ev_id', 'Aircraft_Key','Occurrence_No', 'broad phase of flight', 'specific phase of flight', 'Occurrence', 'phase_no', 'broad_phase_no', 'eventsoe_no']

df_events_sequence_og_edit_2 = df_events_sequence_og[selected_columns].copy()

In [ ]:
df_events_sequence_og_edit_2.head(3)

ev_id  Aircraft_Key  Occurrence_No broad phase of flight  \
0  20080107X00026             1              1               Landing   
1  20080107X00026             2              1         Initial Climb   
2  20080109X00036             1              1               Landing   

  specific phase of flight                 Occurrence  phase_no  \
0                  Landing           Midair collision       550   
1            Initial Climb           Midair collision       350   
2  Landing-Flare/Touchdown  Loss of control on ground       551   

   broad_phase_no  eventsoe_no  
0              55          250  
1              35          250  
2              55          230

In [ ]:
df_events_sequence_og_edit.head(3)

ev_id  Aircraft_Key broad phase of flight  \
0  20080107X00026             1               Landing   
1  20080107X00026             2         Initial Climb   
2  20080109X00036             1               Landing   

  specific phase of flight                 Occurrence  phase_no  \
0                  Landing           Midair collision       550   
1            Initial Climb           Midair collision       350   
2  Landing-Flare/Touchdown  Loss of control on ground       551   

   broad_phase_no  eventsoe_no  
0              55          250  
1              35          250  
2              55          230

In [ ]:
# now I am going to merge df_airfcraft_og_edit, df_events_sequence_og_edit_2, and df_engines_og_edit, 
# these three have the 'Aircraft_Key' whereas events.csv does not

# first merge df_airfcraft_og_edit + df_events_sequence_og_edit_2
df_aircraft_combined = df_airfcraft_og_edit.merge(df_events_sequence_og_edit_2, on=['ev_id', 'Aircraft_Key'], how='left')

# second merge df_aircraft_combined with df_engines_og_edit
df_aircraft_combined = df_aircraft_combined.merge(df_engines_og_edit, on=['ev_id',	'Aircraft_Key'],  how='left') 

# finally merge df_aircraft_combind with df_events_og_edit to put it all together and make the final rebuild!!!
df2 = df_events_og_edit.merge(df_aircraft_combined, on=['ev_id', 'ntsb_no'], how='left') 

In [ ]:
df2.head(3)

ev_id     ntsb_no ev_type            ev_date          ev_city  \
0  20080211X00175  DFW08RA039     ACC  01/10/08 00:00:00  Pitt Meadow, BC   
1  20080107X00026  SEA08LA057     ACC  01/01/08 00:00:00           Sonoma   
2  20080109X00036  DFW08CA054     ACC  01/01/08 00:00:00           Arcola   

  ev_state ev_country latitude longitude ev_nr_apt_id  ... regis_no  \
0      NaN         CA      NaN       NaN          NaN  ...   N530NA   
1       CA        USA  381326N  1222659W          OQ3  ...      NaN   
2       TX        USA  293022N  0952836W          AXH  ...   N579RM   

  Occurrence_No  broad phase of flight  specific phase of flight  \
0           NaN                    NaN                       NaN   
1           NaN                    NaN                       NaN   
2           1.0                Landing   Landing-Flare/Touchdown   

                  Occurrence  phase_no broad_phase_no  eventsoe_no eng_no  \
0                        NaN       NaN            NaN          NaN    NaN   
1                        NaN       NaN            NaN          NaN    NaN   
2  Loss of control on ground     551.0           55.0        230.0    1.0   

  eng_type  
0      NaN  
1      NaN  
2      REC  

[3 rows x 36 columns]

In [ ]:
# Updating the column order

selected_columns = ['ev_id', 'ntsb_no', 'ev_type', 'Aircraft_Key', 'acft_category', 'type_fly', 'acft_make', 'acft_model',  'homebuilt', 'num_eng', 'eng_no', 'eng_type','damage', 'far_part','regis_no','ev_date', 'ev_city', 'ev_state',
       'ev_country', 'latitude', 'longitude', 'ev_nr_apt_id', 'apt_name',
       'ev_highest_injury', 'inj_tot_f', 'inj_tot_s', 'inj_tot_m', 'inj_tot_n',
       'wx_cond_basic', 'Occurrence_No','broad phase of flight', 'specific phase of flight', 'Occurrence',
       'phase_no', 'broad_phase_no', 'eventsoe_no']
df2 = df2[selected_columns].copy()

In [ ]:
df2.head()

ev_id     ntsb_no ev_type  Aircraft_Key acft_category type_fly  \
0  20080211X00175  DFW08RA039     ACC           1.0          HELI     EXLD   
1  20080107X00026  SEA08LA057     ACC           NaN           NaN      NaN   
2  20080109X00036  DFW08CA054     ACC           1.0           AIR     PERS   
3  20080109X00036  DFW08CA054     ACC           1.0           AIR     PERS   
4  20080107X00027  DFW08LA055     ACC           1.0           AIR     PERS   

                acft_make acft_model homebuilt  num_eng  ...  inj_tot_m  \
0       Eurocopter France    AS350B3         N      NaN  ...          0   
1                     NaN        NaN       NaN      NaN  ...          0   
2  Micco Aircraft Company   MAC-145B         N      1.0  ...          0   
3  Micco Aircraft Company   MAC-145B         N      1.0  ...          0   
4                 Pilatus   PC-12/45         N      1.0  ...          0   

  inj_tot_n wx_cond_basic Occurrence_No broad phase of flight  \
0         2           NaN           NaN                   NaN   
1         3           VMC           NaN                   NaN   
2         1           VMC           1.0               Landing   
3         1           VMC           2.0               Landing   
4         8           VMC           1.0              Standing   

       specific phase of flight                      Occurrence phase_no  \
0                           NaN                             NaN      NaN   
1                           NaN                             NaN      NaN   
2       Landing-Flare/Touchdown       Loss of control on ground    551.0   
3                       Landing                Runway excursion    550.0   
4  Standing-Engine(s) Operating  AC/prop/rotor contact w person    153.0   

  broad_phase_no eventsoe_no  
0            NaN         NaN  
1            NaN         NaN  
2           55.0       230.0  
3           55.0       300.0  
4           15.0        81.0  

[5 rows x 36 columns]

In [ ]:
# exporting csv to google drive
#from google.colab import drive
#drive.mount('/content/drive')
path = '/content/drive/My Drive/df2.csv'
with open(path, 'w', encoding = 'utf-8-sig') as f:
  df2.to_csv(f)